// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: message.proto

package server

import (
	"context"

	"SkyeIM/app/message/rpc/internal/logic"
	"SkyeIM/app/message/rpc/internal/svc"
	"SkyeIM/app/message/rpc/message"
)

type MessageServer struct {
	svcCtx *svc.ServiceContext
	message.UnimplementedMessageServer
}

func NewMessageServer(svcCtx *svc.ServiceContext) *MessageServer {
	return &MessageServer{
		svcCtx: svcCtx,
	}
}

// 发送消息（存储到数据库）
func (s *MessageServer) SendMessage(ctx context.Context, in *message.SendMessageReq) (*message.SendMessageResp, error) {
	l := logic.NewSendMessageLogic(ctx, s.svcCtx)
	return l.SendMessage(in)
}

// 获取历史消息列表（分页）
func (s *MessageServer) GetMessageList(ctx context.Context, in *message.GetMessageListReq) (*message.GetMessageListResp, error) {
	l := logic.NewGetMessageListLogic(ctx, s.svcCtx)
	return l.GetMessageList(in)
}

// 标记消息为已读
func (s *MessageServer) MarkAsRead(ctx context.Context, in *message.MarkAsReadReq) (*message.MarkAsReadResp, error) {
	l := logic.NewMarkAsReadLogic(ctx, s.svcCtx)
	return l.MarkAsRead(in)
}

// 获取未读消息数量
func (s *MessageServer) GetUnreadCount(ctx context.Context, in *message.GetUnreadCountReq) (*message.GetUnreadCountResp, error) {
	l := logic.NewGetUnreadCountLogic(ctx, s.svcCtx)
	return l.GetUnreadCount(in)
}

// 获取与某用户的未读消息
func (s *MessageServer) GetUnreadMessages(ctx context.Context, in *message.GetUnreadMessagesReq) (*message.GetUnreadMessagesResp, error) {
	l := logic.NewGetUnreadMessagesLogic(ctx, s.svcCtx)
	return l.GetUnreadMessages(in)
}
