// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: friend.proto

package friendclient

import (
	"context"

	"SkyeIM/app/friend/rpc/friend"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AddFriendRequestReq      = friend.AddFriendRequestReq
	AddFriendRequestResp     = friend.AddFriendRequestResp
	DeleteFriendReq          = friend.DeleteFriendReq
	DeleteFriendResp         = friend.DeleteFriendResp
	FriendInfo               = friend.FriendInfo
	FriendRequestInfo        = friend.FriendRequestInfo
	GetBlacklistReq          = friend.GetBlacklistReq
	GetBlacklistResp         = friend.GetBlacklistResp
	GetFriendListReq         = friend.GetFriendListReq
	GetFriendListResp        = friend.GetFriendListResp
	GetFriendRequestListReq  = friend.GetFriendRequestListReq
	GetFriendRequestListResp = friend.GetFriendRequestListResp
	GetSentRequestListReq    = friend.GetSentRequestListReq
	GetSentRequestListResp   = friend.GetSentRequestListResp
	HandleFriendRequestReq   = friend.HandleFriendRequestReq
	HandleFriendRequestResp  = friend.HandleFriendRequestResp
	IsFriendReq              = friend.IsFriendReq
	IsFriendResp             = friend.IsFriendResp
	SetBlacklistReq          = friend.SetBlacklistReq
	SetBlacklistResp         = friend.SetBlacklistResp
	UpdateFriendRemarkReq    = friend.UpdateFriendRemarkReq
	UpdateFriendRemarkResp   = friend.UpdateFriendRemarkResp

	Friend interface {
		// ==================== 好友申请相关 ====================
		AddFriendRequest(ctx context.Context, in *AddFriendRequestReq, opts ...grpc.CallOption) (*AddFriendRequestResp, error)
		// 获取收到的好友申请列表
		GetFriendRequestList(ctx context.Context, in *GetFriendRequestListReq, opts ...grpc.CallOption) (*GetFriendRequestListResp, error)
		// 获取发出的好友申请列表
		GetSentRequestList(ctx context.Context, in *GetSentRequestListReq, opts ...grpc.CallOption) (*GetSentRequestListResp, error)
		// 处理好友申请（同意/拒绝）
		HandleFriendRequest(ctx context.Context, in *HandleFriendRequestReq, opts ...grpc.CallOption) (*HandleFriendRequestResp, error)
		// ==================== 好友关系相关 ====================
		GetFriendList(ctx context.Context, in *GetFriendListReq, opts ...grpc.CallOption) (*GetFriendListResp, error)
		// 删除好友
		DeleteFriend(ctx context.Context, in *DeleteFriendReq, opts ...grpc.CallOption) (*DeleteFriendResp, error)
		// 更新好友备注
		UpdateFriendRemark(ctx context.Context, in *UpdateFriendRemarkReq, opts ...grpc.CallOption) (*UpdateFriendRemarkResp, error)
		// 设置黑名单（拉黑/取消拉黑）
		SetBlacklist(ctx context.Context, in *SetBlacklistReq, opts ...grpc.CallOption) (*SetBlacklistResp, error)
		// 获取黑名单列表
		GetBlacklist(ctx context.Context, in *GetBlacklistReq, opts ...grpc.CallOption) (*GetBlacklistResp, error)
		// ==================== 辅助查询 ====================
		IsFriend(ctx context.Context, in *IsFriendReq, opts ...grpc.CallOption) (*IsFriendResp, error)
	}

	defaultFriend struct {
		cli zrpc.Client
	}
)

func NewFriend(cli zrpc.Client) Friend {
	return &defaultFriend{
		cli: cli,
	}
}

// ==================== 好友申请相关 ====================
func (m *defaultFriend) AddFriendRequest(ctx context.Context, in *AddFriendRequestReq, opts ...grpc.CallOption) (*AddFriendRequestResp, error) {
	client := friend.NewFriendClient(m.cli.Conn())
	return client.AddFriendRequest(ctx, in, opts...)
}

// 获取收到的好友申请列表
func (m *defaultFriend) GetFriendRequestList(ctx context.Context, in *GetFriendRequestListReq, opts ...grpc.CallOption) (*GetFriendRequestListResp, error) {
	client := friend.NewFriendClient(m.cli.Conn())
	return client.GetFriendRequestList(ctx, in, opts...)
}

// 获取发出的好友申请列表
func (m *defaultFriend) GetSentRequestList(ctx context.Context, in *GetSentRequestListReq, opts ...grpc.CallOption) (*GetSentRequestListResp, error) {
	client := friend.NewFriendClient(m.cli.Conn())
	return client.GetSentRequestList(ctx, in, opts...)
}

// 处理好友申请（同意/拒绝）
func (m *defaultFriend) HandleFriendRequest(ctx context.Context, in *HandleFriendRequestReq, opts ...grpc.CallOption) (*HandleFriendRequestResp, error) {
	client := friend.NewFriendClient(m.cli.Conn())
	return client.HandleFriendRequest(ctx, in, opts...)
}

// ==================== 好友关系相关 ====================
func (m *defaultFriend) GetFriendList(ctx context.Context, in *GetFriendListReq, opts ...grpc.CallOption) (*GetFriendListResp, error) {
	client := friend.NewFriendClient(m.cli.Conn())
	return client.GetFriendList(ctx, in, opts...)
}

// 删除好友
func (m *defaultFriend) DeleteFriend(ctx context.Context, in *DeleteFriendReq, opts ...grpc.CallOption) (*DeleteFriendResp, error) {
	client := friend.NewFriendClient(m.cli.Conn())
	return client.DeleteFriend(ctx, in, opts...)
}

// 更新好友备注
func (m *defaultFriend) UpdateFriendRemark(ctx context.Context, in *UpdateFriendRemarkReq, opts ...grpc.CallOption) (*UpdateFriendRemarkResp, error) {
	client := friend.NewFriendClient(m.cli.Conn())
	return client.UpdateFriendRemark(ctx, in, opts...)
}

// 设置黑名单（拉黑/取消拉黑）
func (m *defaultFriend) SetBlacklist(ctx context.Context, in *SetBlacklistReq, opts ...grpc.CallOption) (*SetBlacklistResp, error) {
	client := friend.NewFriendClient(m.cli.Conn())
	return client.SetBlacklist(ctx, in, opts...)
}

// 获取黑名单列表
func (m *defaultFriend) GetBlacklist(ctx context.Context, in *GetBlacklistReq, opts ...grpc.CallOption) (*GetBlacklistResp, error) {
	client := friend.NewFriendClient(m.cli.Conn())
	return client.GetBlacklist(ctx, in, opts...)
}

// ==================== 辅助查询 ====================
func (m *defaultFriend) IsFriend(ctx context.Context, in *IsFriendReq, opts ...grpc.CallOption) (*IsFriendResp, error) {
	client := friend.NewFriendClient(m.cli.Conn())
	return client.IsFriend(ctx, in, opts...)
}
