// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: friend.proto

package server

import (
	"context"

	"SkyeIM/app/friend/rpc/friend"
	"SkyeIM/app/friend/rpc/internal/logic"
	"SkyeIM/app/friend/rpc/internal/svc"
)

type FriendServer struct {
	svcCtx *svc.ServiceContext
	friend.UnimplementedFriendServer
}

func NewFriendServer(svcCtx *svc.ServiceContext) *FriendServer {
	return &FriendServer{
		svcCtx: svcCtx,
	}
}

// ==================== 好友申请相关 ====================
func (s *FriendServer) AddFriendRequest(ctx context.Context, in *friend.AddFriendRequestReq) (*friend.AddFriendRequestResp, error) {
	l := logic.NewAddFriendRequestLogic(ctx, s.svcCtx)
	return l.AddFriendRequest(in)
}

// 获取收到的好友申请列表
func (s *FriendServer) GetFriendRequestList(ctx context.Context, in *friend.GetFriendRequestListReq) (*friend.GetFriendRequestListResp, error) {
	l := logic.NewGetFriendRequestListLogic(ctx, s.svcCtx)
	return l.GetFriendRequestList(in)
}

// 获取发出的好友申请列表
func (s *FriendServer) GetSentRequestList(ctx context.Context, in *friend.GetSentRequestListReq) (*friend.GetSentRequestListResp, error) {
	l := logic.NewGetSentRequestListLogic(ctx, s.svcCtx)
	return l.GetSentRequestList(in)
}

// 处理好友申请（同意/拒绝）
func (s *FriendServer) HandleFriendRequest(ctx context.Context, in *friend.HandleFriendRequestReq) (*friend.HandleFriendRequestResp, error) {
	l := logic.NewHandleFriendRequestLogic(ctx, s.svcCtx)
	return l.HandleFriendRequest(in)
}

// ==================== 好友关系相关 ====================
func (s *FriendServer) GetFriendList(ctx context.Context, in *friend.GetFriendListReq) (*friend.GetFriendListResp, error) {
	l := logic.NewGetFriendListLogic(ctx, s.svcCtx)
	return l.GetFriendList(in)
}

// 删除好友
func (s *FriendServer) DeleteFriend(ctx context.Context, in *friend.DeleteFriendReq) (*friend.DeleteFriendResp, error) {
	l := logic.NewDeleteFriendLogic(ctx, s.svcCtx)
	return l.DeleteFriend(in)
}

// 更新好友备注
func (s *FriendServer) UpdateFriendRemark(ctx context.Context, in *friend.UpdateFriendRemarkReq) (*friend.UpdateFriendRemarkResp, error) {
	l := logic.NewUpdateFriendRemarkLogic(ctx, s.svcCtx)
	return l.UpdateFriendRemark(in)
}

// 设置黑名单（拉黑/取消拉黑）
func (s *FriendServer) SetBlacklist(ctx context.Context, in *friend.SetBlacklistReq) (*friend.SetBlacklistResp, error) {
	l := logic.NewSetBlacklistLogic(ctx, s.svcCtx)
	return l.SetBlacklist(in)
}

// 获取黑名单列表
func (s *FriendServer) GetBlacklist(ctx context.Context, in *friend.GetBlacklistReq) (*friend.GetBlacklistResp, error) {
	l := logic.NewGetBlacklistLogic(ctx, s.svcCtx)
	return l.GetBlacklist(in)
}

// ==================== 辅助查询 ====================
func (s *FriendServer) IsFriend(ctx context.Context, in *friend.IsFriendReq) (*friend.IsFriendResp, error) {
	l := logic.NewIsFriendLogic(ctx, s.svcCtx)
	return l.IsFriend(in)
}
