// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	imFriendRequestFieldNames          = builder.RawFieldNames(&ImFriendRequest{})
	imFriendRequestRows                = strings.Join(imFriendRequestFieldNames, ",")
	imFriendRequestRowsExpectAutoSet   = strings.Join(stringx.Remove(imFriendRequestFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	imFriendRequestRowsWithPlaceHolder = strings.Join(stringx.Remove(imFriendRequestFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheImFriendRequestIdPrefix = "cache:imFriendRequest:id:"
)

type (
	imFriendRequestModel interface {
		Insert(ctx context.Context, data *ImFriendRequest) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*ImFriendRequest, error)
		Update(ctx context.Context, data *ImFriendRequest) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultImFriendRequestModel struct {
		sqlc.CachedConn
		table string
	}

	ImFriendRequest struct {
		Id         uint64    `db:"id"`
		FromUserId uint64    `db:"from_user_id"` // 发起人ID
		ToUserId   uint64    `db:"to_user_id"`   // 接收人ID
		Message    string    `db:"message"`      // 验证消息
		Status     int64     `db:"status"`       // 0-待处理 1-已同意 2-已拒绝
		CreatedAt  time.Time `db:"created_at"`
		UpdatedAt  time.Time `db:"updated_at"`
	}
)

func newImFriendRequestModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultImFriendRequestModel {
	return &defaultImFriendRequestModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`im_friend_request`",
	}
}

func (m *defaultImFriendRequestModel) Delete(ctx context.Context, id uint64) error {
	imFriendRequestIdKey := fmt.Sprintf("%s%v", cacheImFriendRequestIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, imFriendRequestIdKey)
	return err
}

func (m *defaultImFriendRequestModel) FindOne(ctx context.Context, id uint64) (*ImFriendRequest, error) {
	imFriendRequestIdKey := fmt.Sprintf("%s%v", cacheImFriendRequestIdPrefix, id)
	var resp ImFriendRequest
	err := m.QueryRowCtx(ctx, &resp, imFriendRequestIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", imFriendRequestRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultImFriendRequestModel) Insert(ctx context.Context, data *ImFriendRequest) (sql.Result, error) {
	imFriendRequestIdKey := fmt.Sprintf("%s%v", cacheImFriendRequestIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?)", m.table, imFriendRequestRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.FromUserId, data.ToUserId, data.Message, data.Status)
	}, imFriendRequestIdKey)
	return ret, err
}

func (m *defaultImFriendRequestModel) Update(ctx context.Context, data *ImFriendRequest) error {
	imFriendRequestIdKey := fmt.Sprintf("%s%v", cacheImFriendRequestIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, imFriendRequestRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.FromUserId, data.ToUserId, data.Message, data.Status, data.Id)
	}, imFriendRequestIdKey)
	return err
}

func (m *defaultImFriendRequestModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheImFriendRequestIdPrefix, primary)
}

func (m *defaultImFriendRequestModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", imFriendRequestRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultImFriendRequestModel) tableName() string {
	return m.table
}
