// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	imFriendFieldNames          = builder.RawFieldNames(&ImFriend{})
	imFriendRows                = strings.Join(imFriendFieldNames, ",")
	imFriendRowsExpectAutoSet   = strings.Join(stringx.Remove(imFriendFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	imFriendRowsWithPlaceHolder = strings.Join(stringx.Remove(imFriendFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheImFriendIdPrefix             = "cache:imFriend:id:"
	cacheImFriendUserIdFriendIdPrefix = "cache:imFriend:userId:friendId:"
)

type (
	imFriendModel interface {
		Insert(ctx context.Context, data *ImFriend) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*ImFriend, error)
		FindOneByUserIdFriendId(ctx context.Context, userId uint64, friendId uint64) (*ImFriend, error)
		Update(ctx context.Context, data *ImFriend) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultImFriendModel struct {
		sqlc.CachedConn
		table string
	}

	ImFriend struct {
		Id        uint64    `db:"id"`
		UserId    uint64    `db:"user_id"`   // 用户ID
		FriendId  uint64    `db:"friend_id"` // 好友ID
		Remark    string    `db:"remark"`    // 好友备注
		Status    int64     `db:"status"`    // 1-正常 2-拉黑
		CreatedAt time.Time `db:"created_at"`
		UpdatedAt time.Time `db:"updated_at"`
	}
)

func newImFriendModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultImFriendModel {
	return &defaultImFriendModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`im_friend`",
	}
}

func (m *defaultImFriendModel) Delete(ctx context.Context, id uint64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	imFriendIdKey := fmt.Sprintf("%s%v", cacheImFriendIdPrefix, id)
	imFriendUserIdFriendIdKey := fmt.Sprintf("%s%v:%v", cacheImFriendUserIdFriendIdPrefix, data.UserId, data.FriendId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, imFriendIdKey, imFriendUserIdFriendIdKey)
	return err
}

func (m *defaultImFriendModel) FindOne(ctx context.Context, id uint64) (*ImFriend, error) {
	imFriendIdKey := fmt.Sprintf("%s%v", cacheImFriendIdPrefix, id)
	var resp ImFriend
	err := m.QueryRowCtx(ctx, &resp, imFriendIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", imFriendRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultImFriendModel) FindOneByUserIdFriendId(ctx context.Context, userId uint64, friendId uint64) (*ImFriend, error) {
	imFriendUserIdFriendIdKey := fmt.Sprintf("%s%v:%v", cacheImFriendUserIdFriendIdPrefix, userId, friendId)
	var resp ImFriend
	err := m.QueryRowIndexCtx(ctx, &resp, imFriendUserIdFriendIdKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `user_id` = ? and `friend_id` = ? limit 1", imFriendRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, userId, friendId); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultImFriendModel) Insert(ctx context.Context, data *ImFriend) (sql.Result, error) {
	imFriendIdKey := fmt.Sprintf("%s%v", cacheImFriendIdPrefix, data.Id)
	imFriendUserIdFriendIdKey := fmt.Sprintf("%s%v:%v", cacheImFriendUserIdFriendIdPrefix, data.UserId, data.FriendId)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?)", m.table, imFriendRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.UserId, data.FriendId, data.Remark, data.Status)
	}, imFriendIdKey, imFriendUserIdFriendIdKey)
	return ret, err
}

func (m *defaultImFriendModel) Update(ctx context.Context, newData *ImFriend) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	imFriendIdKey := fmt.Sprintf("%s%v", cacheImFriendIdPrefix, data.Id)
	imFriendUserIdFriendIdKey := fmt.Sprintf("%s%v:%v", cacheImFriendUserIdFriendIdPrefix, data.UserId, data.FriendId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, imFriendRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.UserId, newData.FriendId, newData.Remark, newData.Status, newData.Id)
	}, imFriendIdKey, imFriendUserIdFriendIdKey)
	return err
}

func (m *defaultImFriendModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheImFriendIdPrefix, primary)
}

func (m *defaultImFriendModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", imFriendRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultImFriendModel) tableName() string {
	return m.table
}
