// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	message "SkyeIM/app/message/api/internal/handler/message"
	"SkyeIM/app/message/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// 获取会话列表（最近联系人）
				Method:  http.MethodGet,
				Path:    "/conversations",
				Handler: message.GetConversationsHandler(serverCtx),
			},
			{
				// 获取与某用户的历史消息
				Method:  http.MethodGet,
				Path:    "/history",
				Handler: message.GetMessageHistoryHandler(serverCtx),
			},
			{
				// 标记消息为已读
				Method:  http.MethodPost,
				Path:    "/read",
				Handler: message.MarkAsReadHandler(serverCtx),
			},
			{
				// 获取未读消息数
				Method:  http.MethodGet,
				Path:    "/unread/count",
				Handler: message.GetUnreadCountHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1/message"),
	)
}
