// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	message "SkyeIM/app/message/api/internal/handler/message"
	"SkyeIM/app/message/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// 获取@我的消息列表
				Method:  http.MethodGet,
				Path:    "/at-me",
				Handler: message.GetAtMeMessagesHandler(serverCtx),
			},
			{
				// 获取会话列表（最近联系人）
				Method:  http.MethodGet,
				Path:    "/conversations",
				Handler: message.GetConversationsHandler(serverCtx),
			},
			{
				// 获取群聊历史消息
				Method:  http.MethodGet,
				Path:    "/group/history",
				Handler: message.GetGroupMessageHistoryHandler(serverCtx),
			},
			{
				// 群聊已读上报（更新readSeq）
				Method:  http.MethodPost,
				Path:    "/group/read",
				Handler: message.MarkGroupReadHandler(serverCtx),
			},
			{
				// 群聊离线同步（按seq拉取）
				Method:  http.MethodGet,
				Path:    "/group/sync",
				Handler: message.GetGroupSyncHandler(serverCtx),
			},
			{
				// 获取与某用户的历史消息
				Method:  http.MethodGet,
				Path:    "/history",
				Handler: message.GetMessageHistoryHandler(serverCtx),
			},
			{
				// 私聊离线同步（拉取剩余离线消息）
				Method:  http.MethodGet,
				Path:    "/offline",
				Handler: message.GetPrivateOfflineSyncHandler(serverCtx),
			},
			{
				// 标记私聊消息为已读
				Method:  http.MethodPost,
				Path:    "/read",
				Handler: message.MarkAsReadHandler(serverCtx),
			},
			{
				// 模糊搜索聊天记录
				Method:  http.MethodGet,
				Path:    "/search",
				Handler: message.SearchMessageHandler(serverCtx),
			},
			{
				// 获取未读消息数（私聊）
				Method:  http.MethodGet,
				Path:    "/unread/count",
				Handler: message.GetUnreadCountHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1/message"),
	)
}
