// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: message.proto

package messageclient

import (
	"context"

	"SkyeIM/app/message/rpc/message"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	GetMessageListReq     = message.GetMessageListReq
	GetMessageListResp    = message.GetMessageListResp
	GetUnreadCountReq     = message.GetUnreadCountReq
	GetUnreadCountResp    = message.GetUnreadCountResp
	GetUnreadMessagesReq  = message.GetUnreadMessagesReq
	GetUnreadMessagesResp = message.GetUnreadMessagesResp
	MarkAsReadReq         = message.MarkAsReadReq
	MarkAsReadResp        = message.MarkAsReadResp
	MessageInfo           = message.MessageInfo
	SendMessageReq        = message.SendMessageReq
	SendMessageResp       = message.SendMessageResp

	Message interface {
		// 发送消息（存储到数据库）
		SendMessage(ctx context.Context, in *SendMessageReq, opts ...grpc.CallOption) (*SendMessageResp, error)
		// 获取历史消息列表（分页）
		GetMessageList(ctx context.Context, in *GetMessageListReq, opts ...grpc.CallOption) (*GetMessageListResp, error)
		// 标记消息为已读
		MarkAsRead(ctx context.Context, in *MarkAsReadReq, opts ...grpc.CallOption) (*MarkAsReadResp, error)
		// 获取未读消息数量
		GetUnreadCount(ctx context.Context, in *GetUnreadCountReq, opts ...grpc.CallOption) (*GetUnreadCountResp, error)
		// 获取与某用户的未读消息
		GetUnreadMessages(ctx context.Context, in *GetUnreadMessagesReq, opts ...grpc.CallOption) (*GetUnreadMessagesResp, error)
	}

	defaultMessage struct {
		cli zrpc.Client
	}
)

func NewMessage(cli zrpc.Client) Message {
	return &defaultMessage{
		cli: cli,
	}
}

// 发送消息（存储到数据库）
func (m *defaultMessage) SendMessage(ctx context.Context, in *SendMessageReq, opts ...grpc.CallOption) (*SendMessageResp, error) {
	client := message.NewMessageClient(m.cli.Conn())
	return client.SendMessage(ctx, in, opts...)
}

// 获取历史消息列表（分页）
func (m *defaultMessage) GetMessageList(ctx context.Context, in *GetMessageListReq, opts ...grpc.CallOption) (*GetMessageListResp, error) {
	client := message.NewMessageClient(m.cli.Conn())
	return client.GetMessageList(ctx, in, opts...)
}

// 标记消息为已读
func (m *defaultMessage) MarkAsRead(ctx context.Context, in *MarkAsReadReq, opts ...grpc.CallOption) (*MarkAsReadResp, error) {
	client := message.NewMessageClient(m.cli.Conn())
	return client.MarkAsRead(ctx, in, opts...)
}

// 获取未读消息数量
func (m *defaultMessage) GetUnreadCount(ctx context.Context, in *GetUnreadCountReq, opts ...grpc.CallOption) (*GetUnreadCountResp, error) {
	client := message.NewMessageClient(m.cli.Conn())
	return client.GetUnreadCount(ctx, in, opts...)
}

// 获取与某用户的未读消息
func (m *defaultMessage) GetUnreadMessages(ctx context.Context, in *GetUnreadMessagesReq, opts ...grpc.CallOption) (*GetUnreadMessagesResp, error) {
	client := message.NewMessageClient(m.cli.Conn())
	return client.GetUnreadMessages(ctx, in, opts...)
}
