// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	groupmgmt "SkyeIM/app/group/api/internal/handler/groupmgmt"
	invitation "SkyeIM/app/group/api/internal/handler/invitation"
	membermgmt "SkyeIM/app/group/api/internal/handler/membermgmt"
	"SkyeIM/app/group/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// Get group info
				Method:  http.MethodGet,
				Path:    "/:groupId",
				Handler: groupmgmt.GetGroupInfoHandler(serverCtx),
			},
			{
				// Create group
				Method:  http.MethodPost,
				Path:    "/create",
				Handler: groupmgmt.CreateGroupHandler(serverCtx),
			},
			{
				// Dismiss group
				Method:  http.MethodPost,
				Path:    "/dismiss",
				Handler: groupmgmt.DismissGroupHandler(serverCtx),
			},
			{
				// Get group list
				Method:  http.MethodGet,
				Path:    "/list",
				Handler: groupmgmt.GetGroupListHandler(serverCtx),
			},
			{
				// Search groups
				Method:  http.MethodGet,
				Path:    "/search",
				Handler: groupmgmt.SearchGroupHandler(serverCtx),
			},
			{
				// Precise group search
				Method:  http.MethodGet,
				Path:    "/search/precise",
				Handler: groupmgmt.SearchGroupPreciseHandler(serverCtx),
			},
			{
				// Update group
				Method:  http.MethodPost,
				Path:    "/update",
				Handler: groupmgmt.UpdateGroupHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1/group"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// Handle group invitation
				Method:  http.MethodPost,
				Path:    "/invitation/handle",
				Handler: invitation.HandleGroupInvitationHandler(serverCtx),
			},
			{
				// Get received invitations
				Method:  http.MethodGet,
				Path:    "/invitation/received",
				Handler: invitation.GetReceivedInvitationsHandler(serverCtx),
			},
			{
				// Send group invitation
				Method:  http.MethodPost,
				Path:    "/invitation/send",
				Handler: invitation.SendGroupInvitationHandler(serverCtx),
			},
			{
				// Get sent invitations
				Method:  http.MethodGet,
				Path:    "/invitation/sent",
				Handler: invitation.GetSentInvitationsHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1/group"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// Invite members
				Method:  http.MethodPost,
				Path:    "/member/invite",
				Handler: membermgmt.InviteMembersHandler(serverCtx),
			},
			{
				// Kick member
				Method:  http.MethodPost,
				Path:    "/member/kick",
				Handler: membermgmt.KickMemberHandler(serverCtx),
			},
			{
				// Get member list
				Method:  http.MethodGet,
				Path:    "/member/list",
				Handler: membermgmt.GetMemberListHandler(serverCtx),
			},
			{
				// Set member mute
				Method:  http.MethodPost,
				Path:    "/member/mute",
				Handler: membermgmt.SetMemberMuteHandler(serverCtx),
			},
			{
				// Set member role
				Method:  http.MethodPost,
				Path:    "/member/role",
				Handler: membermgmt.SetMemberRoleHandler(serverCtx),
			},
			{
				// Quit group
				Method:  http.MethodPost,
				Path:    "/quit",
				Handler: membermgmt.QuitGroupHandler(serverCtx),
			},
			{
				// Update group read seq
				Method:  http.MethodPost,
				Path:    "/read",
				Handler: membermgmt.UpdateGroupReadSeqHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1/group"),
	)
}
