// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	groupmgmt "SkyeIM/app/group/api/internal/handler/groupmgmt"
	invitation "SkyeIM/app/group/api/internal/handler/invitation"
	joinrequest "SkyeIM/app/group/api/internal/handler/joinrequest"
	membermgmt "SkyeIM/app/group/api/internal/handler/membermgmt"
	"SkyeIM/app/group/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// 获取群组详情
				Method:  http.MethodGet,
				Path:    "/:groupId",
				Handler: groupmgmt.GetGroupInfoHandler(serverCtx),
			},
			{
				// 创建群组
				Method:  http.MethodPost,
				Path:    "/create",
				Handler: groupmgmt.CreateGroupHandler(serverCtx),
			},
			{
				// 解散群组
				Method:  http.MethodPost,
				Path:    "/dismiss",
				Handler: groupmgmt.DismissGroupHandler(serverCtx),
			},
			{
				// 获取群组列表
				Method:  http.MethodGet,
				Path:    "/list",
				Handler: groupmgmt.GetGroupListHandler(serverCtx),
			},
			{
				// 搜索群组
				Method:  http.MethodGet,
				Path:    "/search",
				Handler: groupmgmt.SearchGroupHandler(serverCtx),
			},
			{
				// 精确搜索群组
				Method:  http.MethodGet,
				Path:    "/search/precise",
				Handler: groupmgmt.SearchGroupPreciseHandler(serverCtx),
			},
			{
				// 更新群组信息
				Method:  http.MethodPost,
				Path:    "/update",
				Handler: groupmgmt.UpdateGroupHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1/group"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 处理入群邀请
				Method:  http.MethodPost,
				Path:    "/invitation/handle",
				Handler: invitation.HandleGroupInvitationHandler(serverCtx),
			},
			{
				// 获取收到的邀请
				Method:  http.MethodGet,
				Path:    "/invitation/received",
				Handler: invitation.GetReceivedInvitationsHandler(serverCtx),
			},
			{
				// 发送入群邀请
				Method:  http.MethodPost,
				Path:    "/invitation/send",
				Handler: invitation.SendGroupInvitationHandler(serverCtx),
			},
			{
				// 获取已发送的邀请
				Method:  http.MethodGet,
				Path:    "/invitation/sent",
				Handler: invitation.GetSentInvitationsHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1/group"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 处理入群申请
				Method:  http.MethodPost,
				Path:    "/join/handle",
				Handler: joinrequest.HandleJoinRequestHandler(serverCtx),
			},
			{
				// 获取所有管理群组的入群申请
				Method:  http.MethodGet,
				Path:    "/join/received",
				Handler: joinrequest.GetReceivedJoinRequestsHandler(serverCtx),
			},
			{
				// 发送入群申请
				Method:  http.MethodPost,
				Path:    "/join/request",
				Handler: joinrequest.SendJoinRequestHandler(serverCtx),
			},
			{
				// 获取群组的入群申请列表
				Method:  http.MethodGet,
				Path:    "/join/requests",
				Handler: joinrequest.GetGroupJoinRequestsHandler(serverCtx),
			},
			{
				// 获取我发出的入群申请
				Method:  http.MethodGet,
				Path:    "/join/sent",
				Handler: joinrequest.GetSentJoinRequestsHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1/group"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 邀请成员
				Method:  http.MethodPost,
				Path:    "/member/invite",
				Handler: membermgmt.InviteMembersHandler(serverCtx),
			},
			{
				// 踢出成员
				Method:  http.MethodPost,
				Path:    "/member/kick",
				Handler: membermgmt.KickMemberHandler(serverCtx),
			},
			{
				// 获取成员列表
				Method:  http.MethodGet,
				Path:    "/member/list",
				Handler: membermgmt.GetMemberListHandler(serverCtx),
			},
			{
				// 设置成员禁言
				Method:  http.MethodPost,
				Path:    "/member/mute",
				Handler: membermgmt.SetMemberMuteHandler(serverCtx),
			},
			{
				// 设置成员角色
				Method:  http.MethodPost,
				Path:    "/member/role",
				Handler: membermgmt.SetMemberRoleHandler(serverCtx),
			},
			{
				// 退出群组
				Method:  http.MethodPost,
				Path:    "/quit",
				Handler: membermgmt.QuitGroupHandler(serverCtx),
			},
			{
				// 更新群组已读序列号
				Method:  http.MethodPost,
				Path:    "/read",
				Handler: membermgmt.UpdateGroupReadSeqHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1/group"),
	)
}
