// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	imMessageFieldNames          = builder.RawFieldNames(&ImMessage{})
	imMessageRows                = strings.Join(imMessageFieldNames, ",")
	imMessageRowsExpectAutoSet   = strings.Join(stringx.Remove(imMessageFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	imMessageRowsWithPlaceHolder = strings.Join(stringx.Remove(imMessageFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheImAuthImMessageIdPrefix    = "cache:imAuth:imMessage:id:"
	cacheImAuthImMessageMsgIdPrefix = "cache:imAuth:imMessage:msgId:"
)

type (
	imMessageModel interface {
		Insert(ctx context.Context, data *ImMessage) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*ImMessage, error)
		FindOneByMsgId(ctx context.Context, msgId string) (*ImMessage, error)
		Update(ctx context.Context, data *ImMessage) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultImMessageModel struct {
		sqlc.CachedConn
		table string
	}

	ImMessage struct {
		Id          uint64         `db:"id"`           // 自增主键ID
		MsgId       string         `db:"msg_id"`       // 消息唯一标识(客户端生成或雪花算法生成的UUID)
		FromUserId  uint64         `db:"from_user_id"` // 发送者ID
		ToUserId    uint64         `db:"to_user_id"`   // 接收者ID（私聊时有效）
		ChatType    int64          `db:"chat_type"`    // 聊天类型: 1-私聊 2-群聊
		GroupId     sql.NullString `db:"group_id"`     // 群组ID（群聊时使用）
		Seq         uint64         `db:"seq"`          // 消息序列号（用于群聊消息连续性校验和拉取偏移量）
		Content     string         `db:"content"`      // 消息内容
		ContentType int64          `db:"content_type"` // 消息内容类型: 1-文字 2-图片 3-文件 4-语音 5-视频
		Status      int64          `db:"status"`       // 消息状态: 0-未读/未处理 1-已读 2-撤回 3-删除
		CreatedAt   time.Time      `db:"created_at"`   // 创建时间
		UpdatedAt   time.Time      `db:"updated_at"`   // 更新时间
		AtUserIds   sql.NullString `db:"at_user_ids"`  // 被@的用户ID列表,JSON格式,如["123","456"],@all用特殊值"-1"
	}
)

func newImMessageModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultImMessageModel {
	return &defaultImMessageModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`im_message`",
	}
}

func (m *defaultImMessageModel) Delete(ctx context.Context, id uint64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	imAuthImMessageIdKey := fmt.Sprintf("%s%v", cacheImAuthImMessageIdPrefix, id)
	imAuthImMessageMsgIdKey := fmt.Sprintf("%s%v", cacheImAuthImMessageMsgIdPrefix, data.MsgId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, imAuthImMessageIdKey, imAuthImMessageMsgIdKey)
	return err
}

func (m *defaultImMessageModel) FindOne(ctx context.Context, id uint64) (*ImMessage, error) {
	imAuthImMessageIdKey := fmt.Sprintf("%s%v", cacheImAuthImMessageIdPrefix, id)
	var resp ImMessage
	err := m.QueryRowCtx(ctx, &resp, imAuthImMessageIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", imMessageRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultImMessageModel) FindOneByMsgId(ctx context.Context, msgId string) (*ImMessage, error) {
	imAuthImMessageMsgIdKey := fmt.Sprintf("%s%v", cacheImAuthImMessageMsgIdPrefix, msgId)
	var resp ImMessage
	err := m.QueryRowIndexCtx(ctx, &resp, imAuthImMessageMsgIdKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `msg_id` = ? limit 1", imMessageRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, msgId); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultImMessageModel) Insert(ctx context.Context, data *ImMessage) (sql.Result, error) {
	imAuthImMessageIdKey := fmt.Sprintf("%s%v", cacheImAuthImMessageIdPrefix, data.Id)
	imAuthImMessageMsgIdKey := fmt.Sprintf("%s%v", cacheImAuthImMessageMsgIdPrefix, data.MsgId)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, imMessageRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.MsgId, data.FromUserId, data.ToUserId, data.ChatType, data.GroupId, data.Seq, data.Content, data.ContentType, data.Status, data.AtUserIds)
	}, imAuthImMessageIdKey, imAuthImMessageMsgIdKey)
	return ret, err
}

func (m *defaultImMessageModel) Update(ctx context.Context, newData *ImMessage) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	imAuthImMessageIdKey := fmt.Sprintf("%s%v", cacheImAuthImMessageIdPrefix, data.Id)
	imAuthImMessageMsgIdKey := fmt.Sprintf("%s%v", cacheImAuthImMessageMsgIdPrefix, data.MsgId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, imMessageRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.MsgId, newData.FromUserId, newData.ToUserId, newData.ChatType, newData.GroupId, newData.Seq, newData.Content, newData.ContentType, newData.Status, newData.AtUserIds, newData.Id)
	}, imAuthImMessageIdKey, imAuthImMessageMsgIdKey)
	return err
}

func (m *defaultImMessageModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheImAuthImMessageIdPrefix, primary)
}

func (m *defaultImMessageModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", imMessageRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultImMessageModel) tableName() string {
	return m.table
}
