// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type AddFriendRequestReq struct {
	ToUserId int64  `json:"toUserId"`
	Message  string `json:"message,optional"`
}

type AddFriendRequestResp struct {
	RequestId int64 `json:"requestId"`
}

type DeleteFriendReq struct {
	FriendId int64 `path:"friendId"`
}

type Empty struct {
}

type FriendInfo struct {
	Id        int64  `json:"id"`
	FriendId  int64  `json:"friendId"`
	Remark    string `json:"remark"`
	Status    int64  `json:"status"` // 1-正常 2-拉黑
	CreatedAt int64  `json:"createdAt"`
}

type FriendListResp struct {
	List  []FriendInfo `json:"list"`
	Total int64        `json:"total"`
}

type FriendRequestInfo struct {
	Id         int64  `json:"id"`
	FromUserId int64  `json:"fromUserId"`
	ToUserId   int64  `json:"toUserId"`
	Message    string `json:"message"`
	Status     int64  `json:"status"` // 0-待处理 1-已同意 2-已拒绝
	CreatedAt  int64  `json:"createdAt"`
}

type FriendRequestListResp struct {
	List  []FriendRequestInfo `json:"list"`
	Total int64               `json:"total"`
}

type GetFriendReq struct {
	FriendId int64 `path:"friendId"`
}

type HandleFriendRequestReq struct {
	RequestId int64 `path:"requestId"`
	Action    int64 `json:"action"` // 1-同意 2-拒绝
}

type IsFriendResp struct {
	IsFriend bool  `json:"isFriend"`
	Status   int64 `json:"status"` // 0-非好友 1-正常 2-被拉黑
}

type PageReq struct {
	Page     int64 `form:"page,default=1"`
	PageSize int64 `form:"pageSize,default=20"`
}

type SetBlacklistReq struct {
	FriendId int64 `json:"friendId"`
	IsBlack  bool  `json:"isBlack"` // true-拉黑 false-取消拉黑
}

type UpdateRemarkReq struct {
	FriendId int64  `path:"friendId"`
	Remark   string `json:"remark"`
}
