// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	imGroupJoinRequestFieldNames          = builder.RawFieldNames(&ImGroupJoinRequest{})
	imGroupJoinRequestRows                = strings.Join(imGroupJoinRequestFieldNames, ",")
	imGroupJoinRequestRowsExpectAutoSet   = strings.Join(stringx.Remove(imGroupJoinRequestFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	imGroupJoinRequestRowsWithPlaceHolder = strings.Join(stringx.Remove(imGroupJoinRequestFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheImGroupJoinRequestIdPrefix                  = "cache:imGroupJoinRequest:id:"
	cacheImGroupJoinRequestGroupIdUserIdStatusPrefix = "cache:imGroupJoinRequest:groupId:userId:status:"
)

type (
	imGroupJoinRequestModel interface {
		Insert(ctx context.Context, data *ImGroupJoinRequest) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*ImGroupJoinRequest, error)
		FindOneByGroupIdUserIdStatus(ctx context.Context, groupId string, userId uint64, status int64) (*ImGroupJoinRequest, error)
		Update(ctx context.Context, data *ImGroupJoinRequest) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultImGroupJoinRequestModel struct {
		sqlc.CachedConn
		table string
	}

	ImGroupJoinRequest struct {
		Id        uint64        `db:"id"`
		GroupId   string        `db:"group_id"`   // 群组ID
		UserId    uint64        `db:"user_id"`    // 申请人ID
		Message   string        `db:"message"`    // 申请理由
		Status    int64         `db:"status"`     // 0-待处理 1-已同意 2-已拒绝
		HandlerId sql.NullInt64 `db:"handler_id"` // 处理人ID（群主/管理员）
		CreatedAt time.Time     `db:"created_at"`
		UpdatedAt time.Time     `db:"updated_at"`
	}
)

func newImGroupJoinRequestModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultImGroupJoinRequestModel {
	return &defaultImGroupJoinRequestModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`im_group_join_request`",
	}
}

func (m *defaultImGroupJoinRequestModel) Delete(ctx context.Context, id uint64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	imGroupJoinRequestGroupIdUserIdStatusKey := fmt.Sprintf("%s%v:%v:%v", cacheImGroupJoinRequestGroupIdUserIdStatusPrefix, data.GroupId, data.UserId, data.Status)
	imGroupJoinRequestIdKey := fmt.Sprintf("%s%v", cacheImGroupJoinRequestIdPrefix, id)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, imGroupJoinRequestGroupIdUserIdStatusKey, imGroupJoinRequestIdKey)
	return err
}

func (m *defaultImGroupJoinRequestModel) FindOne(ctx context.Context, id uint64) (*ImGroupJoinRequest, error) {
	imGroupJoinRequestIdKey := fmt.Sprintf("%s%v", cacheImGroupJoinRequestIdPrefix, id)
	var resp ImGroupJoinRequest
	err := m.QueryRowCtx(ctx, &resp, imGroupJoinRequestIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", imGroupJoinRequestRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultImGroupJoinRequestModel) FindOneByGroupIdUserIdStatus(ctx context.Context, groupId string, userId uint64, status int64) (*ImGroupJoinRequest, error) {
	imGroupJoinRequestGroupIdUserIdStatusKey := fmt.Sprintf("%s%v:%v:%v", cacheImGroupJoinRequestGroupIdUserIdStatusPrefix, groupId, userId, status)
	var resp ImGroupJoinRequest
	err := m.QueryRowIndexCtx(ctx, &resp, imGroupJoinRequestGroupIdUserIdStatusKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `group_id` = ? and `user_id` = ? and `status` = ? limit 1", imGroupJoinRequestRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, groupId, userId, status); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultImGroupJoinRequestModel) Insert(ctx context.Context, data *ImGroupJoinRequest) (sql.Result, error) {
	imGroupJoinRequestGroupIdUserIdStatusKey := fmt.Sprintf("%s%v:%v:%v", cacheImGroupJoinRequestGroupIdUserIdStatusPrefix, data.GroupId, data.UserId, data.Status)
	imGroupJoinRequestIdKey := fmt.Sprintf("%s%v", cacheImGroupJoinRequestIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?)", m.table, imGroupJoinRequestRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.GroupId, data.UserId, data.Message, data.Status, data.HandlerId)
	}, imGroupJoinRequestGroupIdUserIdStatusKey, imGroupJoinRequestIdKey)
	return ret, err
}

func (m *defaultImGroupJoinRequestModel) Update(ctx context.Context, newData *ImGroupJoinRequest) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	imGroupJoinRequestGroupIdUserIdStatusKey := fmt.Sprintf("%s%v:%v:%v", cacheImGroupJoinRequestGroupIdUserIdStatusPrefix, data.GroupId, data.UserId, data.Status)
	imGroupJoinRequestIdKey := fmt.Sprintf("%s%v", cacheImGroupJoinRequestIdPrefix, data.Id)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, imGroupJoinRequestRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.GroupId, newData.UserId, newData.Message, newData.Status, newData.HandlerId, newData.Id)
	}, imGroupJoinRequestGroupIdUserIdStatusKey, imGroupJoinRequestIdKey)
	return err
}

func (m *defaultImGroupJoinRequestModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheImGroupJoinRequestIdPrefix, primary)
}

func (m *defaultImGroupJoinRequestModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", imGroupJoinRequestRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultImGroupJoinRequestModel) tableName() string {
	return m.table
}
