// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	imGroupFieldNames          = builder.RawFieldNames(&ImGroup{})
	imGroupRows                = strings.Join(imGroupFieldNames, ",")
	imGroupRowsExpectAutoSet   = strings.Join(stringx.Remove(imGroupFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	imGroupRowsWithPlaceHolder = strings.Join(stringx.Remove(imGroupFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheImAuthImGroupIdPrefix      = "cache:imAuth:imGroup:id:"
	cacheImAuthImGroupGroupIdPrefix = "cache:imAuth:imGroup:groupId:"
)

type (
	imGroupModel interface {
		Insert(ctx context.Context, data *ImGroup) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*ImGroup, error)
		FindOneByGroupId(ctx context.Context, groupId string) (*ImGroup, error)
		Update(ctx context.Context, data *ImGroup) error
		Delete(ctx context.Context, id int64) error
	}

	defaultImGroupModel struct {
		sqlc.CachedConn
		table string
	}

	ImGroup struct {
		Id                int64          `db:"id"`
		GroupId           string         `db:"group_id"`            // 群组唯一标识
		Name              string         `db:"name"`                // 群名称
		Avatar            sql.NullString `db:"avatar"`              // 群头像
		OwnerId           int64          `db:"owner_id"`            // 群主ID
		Description       sql.NullString `db:"description"`         // 群描述
		MaxMembers        int64          `db:"max_members"`         // 最大成员数
		MemberCount       int64          `db:"member_count"`        // 当前成员数
		Status            int64          `db:"status"`              // 状态: 1-正常 2-已解散
		InviteConfirmMode int64          `db:"invite_confirm_mode"` // 邀请确认模式: 0-直接加入 1-需要确认（默认）
		CreatedAt         time.Time      `db:"created_at"`
		UpdatedAt         time.Time      `db:"updated_at"`
	}
)

func newImGroupModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultImGroupModel {
	return &defaultImGroupModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`im_group`",
	}
}

func (m *defaultImGroupModel) Delete(ctx context.Context, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	imAuthImGroupGroupIdKey := fmt.Sprintf("%s%v", cacheImAuthImGroupGroupIdPrefix, data.GroupId)
	imAuthImGroupIdKey := fmt.Sprintf("%s%v", cacheImAuthImGroupIdPrefix, id)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, imAuthImGroupGroupIdKey, imAuthImGroupIdKey)
	return err
}

func (m *defaultImGroupModel) FindOne(ctx context.Context, id int64) (*ImGroup, error) {
	imAuthImGroupIdKey := fmt.Sprintf("%s%v", cacheImAuthImGroupIdPrefix, id)
	var resp ImGroup
	err := m.QueryRowCtx(ctx, &resp, imAuthImGroupIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", imGroupRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultImGroupModel) FindOneByGroupId(ctx context.Context, groupId string) (*ImGroup, error) {
	imAuthImGroupGroupIdKey := fmt.Sprintf("%s%v", cacheImAuthImGroupGroupIdPrefix, groupId)
	var resp ImGroup
	err := m.QueryRowIndexCtx(ctx, &resp, imAuthImGroupGroupIdKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `group_id` = ? limit 1", imGroupRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, groupId); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultImGroupModel) Insert(ctx context.Context, data *ImGroup) (sql.Result, error) {
	imAuthImGroupGroupIdKey := fmt.Sprintf("%s%v", cacheImAuthImGroupGroupIdPrefix, data.GroupId)
	imAuthImGroupIdKey := fmt.Sprintf("%s%v", cacheImAuthImGroupIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, imGroupRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.GroupId, data.Name, data.Avatar, data.OwnerId, data.Description, data.MaxMembers, data.MemberCount, data.Status, data.InviteConfirmMode)
	}, imAuthImGroupGroupIdKey, imAuthImGroupIdKey)
	return ret, err
}

func (m *defaultImGroupModel) Update(ctx context.Context, newData *ImGroup) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	imAuthImGroupGroupIdKey := fmt.Sprintf("%s%v", cacheImAuthImGroupGroupIdPrefix, data.GroupId)
	imAuthImGroupIdKey := fmt.Sprintf("%s%v", cacheImAuthImGroupIdPrefix, data.Id)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, imGroupRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.GroupId, newData.Name, newData.Avatar, newData.OwnerId, newData.Description, newData.MaxMembers, newData.MemberCount, newData.Status, newData.InviteConfirmMode, newData.Id)
	}, imAuthImGroupGroupIdKey, imAuthImGroupIdKey)
	return err
}

func (m *defaultImGroupModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheImAuthImGroupIdPrefix, primary)
}

func (m *defaultImGroupModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", imGroupRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultImGroupModel) tableName() string {
	return m.table
}
