// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	imGroupMemberFieldNames          = builder.RawFieldNames(&ImGroupMember{})
	imGroupMemberRows                = strings.Join(imGroupMemberFieldNames, ",")
	imGroupMemberRowsExpectAutoSet   = strings.Join(stringx.Remove(imGroupMemberFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	imGroupMemberRowsWithPlaceHolder = strings.Join(stringx.Remove(imGroupMemberFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheImGroupMemberIdPrefix            = "cache:imGroupMember:id:"
	cacheImGroupMemberGroupIdUserIdPrefix = "cache:imGroupMember:groupId:userId:"
)

type (
	imGroupMemberModel interface {
		Insert(ctx context.Context, data *ImGroupMember) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*ImGroupMember, error)
		FindOneByGroupIdUserId(ctx context.Context, groupId string, userId int64) (*ImGroupMember, error)
		Update(ctx context.Context, data *ImGroupMember) error
		Delete(ctx context.Context, id int64) error
	}

	defaultImGroupMemberModel struct {
		sqlc.CachedConn
		table string
	}

	ImGroupMember struct {
		Id       int64          `db:"id"`
		GroupId  string         `db:"group_id"` // 群组ID
		UserId   int64          `db:"user_id"`  // 用户ID
		Role     int64          `db:"role"`     // 角色: 1-群主 2-管理员 3-普通成员
		Nickname sql.NullString `db:"nickname"` // 群昵称
		Mute     int64          `db:"mute"`     // 是否禁言: 0-否 1-是
		ReadSeq  uint64         `db:"read_seq"` // 已读消息Seq
		JoinedAt time.Time      `db:"joined_at"`
	}
)

func newImGroupMemberModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultImGroupMemberModel {
	return &defaultImGroupMemberModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`im_group_member`",
	}
}

func (m *defaultImGroupMemberModel) Delete(ctx context.Context, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	imGroupMemberGroupIdUserIdKey := fmt.Sprintf("%s%v:%v", cacheImGroupMemberGroupIdUserIdPrefix, data.GroupId, data.UserId)
	imGroupMemberIdKey := fmt.Sprintf("%s%v", cacheImGroupMemberIdPrefix, id)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, imGroupMemberGroupIdUserIdKey, imGroupMemberIdKey)
	return err
}

func (m *defaultImGroupMemberModel) FindOne(ctx context.Context, id int64) (*ImGroupMember, error) {
	imGroupMemberIdKey := fmt.Sprintf("%s%v", cacheImGroupMemberIdPrefix, id)
	var resp ImGroupMember
	err := m.QueryRowCtx(ctx, &resp, imGroupMemberIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", imGroupMemberRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultImGroupMemberModel) FindOneByGroupIdUserId(ctx context.Context, groupId string, userId int64) (*ImGroupMember, error) {
	imGroupMemberGroupIdUserIdKey := fmt.Sprintf("%s%v:%v", cacheImGroupMemberGroupIdUserIdPrefix, groupId, userId)
	var resp ImGroupMember
	err := m.QueryRowIndexCtx(ctx, &resp, imGroupMemberGroupIdUserIdKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `group_id` = ? and `user_id` = ? limit 1", imGroupMemberRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, groupId, userId); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultImGroupMemberModel) Insert(ctx context.Context, data *ImGroupMember) (sql.Result, error) {
	imGroupMemberGroupIdUserIdKey := fmt.Sprintf("%s%v:%v", cacheImGroupMemberGroupIdUserIdPrefix, data.GroupId, data.UserId)
	imGroupMemberIdKey := fmt.Sprintf("%s%v", cacheImGroupMemberIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?)", m.table, imGroupMemberRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.GroupId, data.UserId, data.Role, data.Nickname, data.Mute, data.ReadSeq, data.JoinedAt)
	}, imGroupMemberGroupIdUserIdKey, imGroupMemberIdKey)
	return ret, err
}

func (m *defaultImGroupMemberModel) Update(ctx context.Context, newData *ImGroupMember) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	imGroupMemberGroupIdUserIdKey := fmt.Sprintf("%s%v:%v", cacheImGroupMemberGroupIdUserIdPrefix, data.GroupId, data.UserId)
	imGroupMemberIdKey := fmt.Sprintf("%s%v", cacheImGroupMemberIdPrefix, data.Id)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, imGroupMemberRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.GroupId, newData.UserId, newData.Role, newData.Nickname, newData.Mute, newData.ReadSeq, newData.JoinedAt, newData.Id)
	}, imGroupMemberGroupIdUserIdKey, imGroupMemberIdKey)
	return err
}

func (m *defaultImGroupMemberModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheImGroupMemberIdPrefix, primary)
}

func (m *defaultImGroupMemberModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", imGroupMemberRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultImGroupMemberModel) tableName() string {
	return m.table
}
