// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: group.proto

package groupclient

import (
	"context"

	"SkyeIM/app/group/rpc/group"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CheckMembershipReq                 = group.CheckMembershipReq
	CheckMembershipResp                = group.CheckMembershipResp
	CreateGroupReq                     = group.CreateGroupReq
	CreateGroupResp                    = group.CreateGroupResp
	DismissGroupReq                    = group.DismissGroupReq
	DismissGroupResp                   = group.DismissGroupResp
	GetAllManagedGroupJoinRequestsReq  = group.GetAllManagedGroupJoinRequestsReq
	GetAllManagedGroupJoinRequestsResp = group.GetAllManagedGroupJoinRequestsResp
	GetGroupInfoReq                    = group.GetGroupInfoReq
	GetGroupInfoResp                   = group.GetGroupInfoResp
	GetGroupJoinRequestsReq            = group.GetGroupJoinRequestsReq
	GetGroupJoinRequestsResp           = group.GetGroupJoinRequestsResp
	GetJoinedGroupsReq                 = group.GetJoinedGroupsReq
	GetJoinedGroupsResp                = group.GetJoinedGroupsResp
	GetMemberListReq                   = group.GetMemberListReq
	GetMemberListResp                  = group.GetMemberListResp
	GetReceivedInvitationsReq          = group.GetReceivedInvitationsReq
	GetReceivedInvitationsResp         = group.GetReceivedInvitationsResp
	GetSentInvitationsReq              = group.GetSentInvitationsReq
	GetSentInvitationsResp             = group.GetSentInvitationsResp
	GetSentJoinRequestsReq             = group.GetSentJoinRequestsReq
	GetSentJoinRequestsResp            = group.GetSentJoinRequestsResp
	GetUserGroupListReq                = group.GetUserGroupListReq
	GetUserGroupListResp               = group.GetUserGroupListResp
	GroupInfo                          = group.GroupInfo
	GroupInvitationInfo                = group.GroupInvitationInfo
	HandleGroupInvitationReq           = group.HandleGroupInvitationReq
	HandleGroupInvitationResp          = group.HandleGroupInvitationResp
	HandleJoinRequestReq               = group.HandleJoinRequestReq
	HandleJoinRequestResp              = group.HandleJoinRequestResp
	InviteMembersReq                   = group.InviteMembersReq
	InviteMembersResp                  = group.InviteMembersResp
	JoinRequestInfo                    = group.JoinRequestInfo
	KickMemberReq                      = group.KickMemberReq
	KickMemberResp                     = group.KickMemberResp
	MemberInfo                         = group.MemberInfo
	QuitGroupReq                       = group.QuitGroupReq
	QuitGroupResp                      = group.QuitGroupResp
	SearchGroupReq                     = group.SearchGroupReq
	SearchGroupResp                    = group.SearchGroupResp
	SendGroupInvitationReq             = group.SendGroupInvitationReq
	SendGroupInvitationResp            = group.SendGroupInvitationResp
	SendJoinRequestReq                 = group.SendJoinRequestReq
	SendJoinRequestResp                = group.SendJoinRequestResp
	SetMemberMuteReq                   = group.SetMemberMuteReq
	SetMemberMuteResp                  = group.SetMemberMuteResp
	SetMemberRoleReq                   = group.SetMemberRoleReq
	SetMemberRoleResp                  = group.SetMemberRoleResp
	UpdateGroupReadSeqReq              = group.UpdateGroupReadSeqReq
	UpdateGroupReadSeqResp             = group.UpdateGroupReadSeqResp
	UpdateGroupReq                     = group.UpdateGroupReq
	UpdateGroupResp                    = group.UpdateGroupResp

	Group interface {
		// 创建群组
		CreateGroup(ctx context.Context, in *CreateGroupReq, opts ...grpc.CallOption) (*CreateGroupResp, error)
		// 获取群组信息
		GetGroupInfo(ctx context.Context, in *GetGroupInfoReq, opts ...grpc.CallOption) (*GetGroupInfoResp, error)
		// 更新群组信息
		UpdateGroup(ctx context.Context, in *UpdateGroupReq, opts ...grpc.CallOption) (*UpdateGroupResp, error)
		// 解散群组
		DismissGroup(ctx context.Context, in *DismissGroupReq, opts ...grpc.CallOption) (*DismissGroupResp, error)
		// 邀请成员加入群组
		InviteMembers(ctx context.Context, in *InviteMembersReq, opts ...grpc.CallOption) (*InviteMembersResp, error)
		// 踢出成员
		KickMember(ctx context.Context, in *KickMemberReq, opts ...grpc.CallOption) (*KickMemberResp, error)
		// 退出群组
		QuitGroup(ctx context.Context, in *QuitGroupReq, opts ...grpc.CallOption) (*QuitGroupResp, error)
		// 获取群成员列表
		GetMemberList(ctx context.Context, in *GetMemberListReq, opts ...grpc.CallOption) (*GetMemberListResp, error)
		// 获取用户的群组列表
		GetUserGroupList(ctx context.Context, in *GetUserGroupListReq, opts ...grpc.CallOption) (*GetUserGroupListResp, error)
		// 设置成员权限
		SetMemberRole(ctx context.Context, in *SetMemberRoleReq, opts ...grpc.CallOption) (*SetMemberRoleResp, error)
		// 设置成员禁言
		SetMemberMute(ctx context.Context, in *SetMemberMuteReq, opts ...grpc.CallOption) (*SetMemberMuteResp, error)
		// 检查用户是否在群组中
		CheckMembership(ctx context.Context, in *CheckMembershipReq, opts ...grpc.CallOption) (*CheckMembershipResp, error)
		// 更新群组已读进度
		UpdateGroupReadSeq(ctx context.Context, in *UpdateGroupReadSeqReq, opts ...grpc.CallOption) (*UpdateGroupReadSeqResp, error)
		// 获取用户加入的群组列表（包含成员信息如ReadSeq）
		GetJoinedGroups(ctx context.Context, in *GetJoinedGroupsReq, opts ...grpc.CallOption) (*GetJoinedGroupsResp, error)
		// 模糊搜索群组
		SearchGroup(ctx context.Context, in *SearchGroupReq, opts ...grpc.CallOption) (*SearchGroupResp, error)
		// ==================== 群聊邀请相关 ====================
		SendGroupInvitation(ctx context.Context, in *SendGroupInvitationReq, opts ...grpc.CallOption) (*SendGroupInvitationResp, error)
		// 处理群聊邀请（同意/拒绝）
		HandleGroupInvitation(ctx context.Context, in *HandleGroupInvitationReq, opts ...grpc.CallOption) (*HandleGroupInvitationResp, error)
		// 获取收到的群聊邀请列表
		GetReceivedInvitations(ctx context.Context, in *GetReceivedInvitationsReq, opts ...grpc.CallOption) (*GetReceivedInvitationsResp, error)
		// 获取发出的群聊邀请列表
		GetSentInvitations(ctx context.Context, in *GetSentInvitationsReq, opts ...grpc.CallOption) (*GetSentInvitationsResp, error)
		// ==================== 入群申请相关 ====================
		SendJoinRequest(ctx context.Context, in *SendJoinRequestReq, opts ...grpc.CallOption) (*SendJoinRequestResp, error)
		// 处理入群申请（群主/管理员）
		HandleJoinRequest(ctx context.Context, in *HandleJoinRequestReq, opts ...grpc.CallOption) (*HandleJoinRequestResp, error)
		// 获取群的入群申请列表（群主/管理员查看）
		GetGroupJoinRequests(ctx context.Context, in *GetGroupJoinRequestsReq, opts ...grpc.CallOption) (*GetGroupJoinRequestsResp, error)
		// 获取用户发出的入群申请
		GetSentJoinRequests(ctx context.Context, in *GetSentJoinRequestsReq, opts ...grpc.CallOption) (*GetSentJoinRequestsResp, error)
		// 获取所有管理群组的入群申请（通知中心）
		GetAllManagedGroupJoinRequests(ctx context.Context, in *GetAllManagedGroupJoinRequestsReq, opts ...grpc.CallOption) (*GetAllManagedGroupJoinRequestsResp, error)
	}

	defaultGroup struct {
		cli zrpc.Client
	}
)

func NewGroup(cli zrpc.Client) Group {
	return &defaultGroup{
		cli: cli,
	}
}

// 创建群组
func (m *defaultGroup) CreateGroup(ctx context.Context, in *CreateGroupReq, opts ...grpc.CallOption) (*CreateGroupResp, error) {
	client := group.NewGroupClient(m.cli.Conn())
	return client.CreateGroup(ctx, in, opts...)
}

// 获取群组信息
func (m *defaultGroup) GetGroupInfo(ctx context.Context, in *GetGroupInfoReq, opts ...grpc.CallOption) (*GetGroupInfoResp, error) {
	client := group.NewGroupClient(m.cli.Conn())
	return client.GetGroupInfo(ctx, in, opts...)
}

// 更新群组信息
func (m *defaultGroup) UpdateGroup(ctx context.Context, in *UpdateGroupReq, opts ...grpc.CallOption) (*UpdateGroupResp, error) {
	client := group.NewGroupClient(m.cli.Conn())
	return client.UpdateGroup(ctx, in, opts...)
}

// 解散群组
func (m *defaultGroup) DismissGroup(ctx context.Context, in *DismissGroupReq, opts ...grpc.CallOption) (*DismissGroupResp, error) {
	client := group.NewGroupClient(m.cli.Conn())
	return client.DismissGroup(ctx, in, opts...)
}

// 邀请成员加入群组
func (m *defaultGroup) InviteMembers(ctx context.Context, in *InviteMembersReq, opts ...grpc.CallOption) (*InviteMembersResp, error) {
	client := group.NewGroupClient(m.cli.Conn())
	return client.InviteMembers(ctx, in, opts...)
}

// 踢出成员
func (m *defaultGroup) KickMember(ctx context.Context, in *KickMemberReq, opts ...grpc.CallOption) (*KickMemberResp, error) {
	client := group.NewGroupClient(m.cli.Conn())
	return client.KickMember(ctx, in, opts...)
}

// 退出群组
func (m *defaultGroup) QuitGroup(ctx context.Context, in *QuitGroupReq, opts ...grpc.CallOption) (*QuitGroupResp, error) {
	client := group.NewGroupClient(m.cli.Conn())
	return client.QuitGroup(ctx, in, opts...)
}

// 获取群成员列表
func (m *defaultGroup) GetMemberList(ctx context.Context, in *GetMemberListReq, opts ...grpc.CallOption) (*GetMemberListResp, error) {
	client := group.NewGroupClient(m.cli.Conn())
	return client.GetMemberList(ctx, in, opts...)
}

// 获取用户的群组列表
func (m *defaultGroup) GetUserGroupList(ctx context.Context, in *GetUserGroupListReq, opts ...grpc.CallOption) (*GetUserGroupListResp, error) {
	client := group.NewGroupClient(m.cli.Conn())
	return client.GetUserGroupList(ctx, in, opts...)
}

// 设置成员权限
func (m *defaultGroup) SetMemberRole(ctx context.Context, in *SetMemberRoleReq, opts ...grpc.CallOption) (*SetMemberRoleResp, error) {
	client := group.NewGroupClient(m.cli.Conn())
	return client.SetMemberRole(ctx, in, opts...)
}

// 设置成员禁言
func (m *defaultGroup) SetMemberMute(ctx context.Context, in *SetMemberMuteReq, opts ...grpc.CallOption) (*SetMemberMuteResp, error) {
	client := group.NewGroupClient(m.cli.Conn())
	return client.SetMemberMute(ctx, in, opts...)
}

// 检查用户是否在群组中
func (m *defaultGroup) CheckMembership(ctx context.Context, in *CheckMembershipReq, opts ...grpc.CallOption) (*CheckMembershipResp, error) {
	client := group.NewGroupClient(m.cli.Conn())
	return client.CheckMembership(ctx, in, opts...)
}

// 更新群组已读进度
func (m *defaultGroup) UpdateGroupReadSeq(ctx context.Context, in *UpdateGroupReadSeqReq, opts ...grpc.CallOption) (*UpdateGroupReadSeqResp, error) {
	client := group.NewGroupClient(m.cli.Conn())
	return client.UpdateGroupReadSeq(ctx, in, opts...)
}

// 获取用户加入的群组列表（包含成员信息如ReadSeq）
func (m *defaultGroup) GetJoinedGroups(ctx context.Context, in *GetJoinedGroupsReq, opts ...grpc.CallOption) (*GetJoinedGroupsResp, error) {
	client := group.NewGroupClient(m.cli.Conn())
	return client.GetJoinedGroups(ctx, in, opts...)
}

// 模糊搜索群组
func (m *defaultGroup) SearchGroup(ctx context.Context, in *SearchGroupReq, opts ...grpc.CallOption) (*SearchGroupResp, error) {
	client := group.NewGroupClient(m.cli.Conn())
	return client.SearchGroup(ctx, in, opts...)
}

// ==================== 群聊邀请相关 ====================
func (m *defaultGroup) SendGroupInvitation(ctx context.Context, in *SendGroupInvitationReq, opts ...grpc.CallOption) (*SendGroupInvitationResp, error) {
	client := group.NewGroupClient(m.cli.Conn())
	return client.SendGroupInvitation(ctx, in, opts...)
}

// 处理群聊邀请（同意/拒绝）
func (m *defaultGroup) HandleGroupInvitation(ctx context.Context, in *HandleGroupInvitationReq, opts ...grpc.CallOption) (*HandleGroupInvitationResp, error) {
	client := group.NewGroupClient(m.cli.Conn())
	return client.HandleGroupInvitation(ctx, in, opts...)
}

// 获取收到的群聊邀请列表
func (m *defaultGroup) GetReceivedInvitations(ctx context.Context, in *GetReceivedInvitationsReq, opts ...grpc.CallOption) (*GetReceivedInvitationsResp, error) {
	client := group.NewGroupClient(m.cli.Conn())
	return client.GetReceivedInvitations(ctx, in, opts...)
}

// 获取发出的群聊邀请列表
func (m *defaultGroup) GetSentInvitations(ctx context.Context, in *GetSentInvitationsReq, opts ...grpc.CallOption) (*GetSentInvitationsResp, error) {
	client := group.NewGroupClient(m.cli.Conn())
	return client.GetSentInvitations(ctx, in, opts...)
}

// ==================== 入群申请相关 ====================
func (m *defaultGroup) SendJoinRequest(ctx context.Context, in *SendJoinRequestReq, opts ...grpc.CallOption) (*SendJoinRequestResp, error) {
	client := group.NewGroupClient(m.cli.Conn())
	return client.SendJoinRequest(ctx, in, opts...)
}

// 处理入群申请（群主/管理员）
func (m *defaultGroup) HandleJoinRequest(ctx context.Context, in *HandleJoinRequestReq, opts ...grpc.CallOption) (*HandleJoinRequestResp, error) {
	client := group.NewGroupClient(m.cli.Conn())
	return client.HandleJoinRequest(ctx, in, opts...)
}

// 获取群的入群申请列表（群主/管理员查看）
func (m *defaultGroup) GetGroupJoinRequests(ctx context.Context, in *GetGroupJoinRequestsReq, opts ...grpc.CallOption) (*GetGroupJoinRequestsResp, error) {
	client := group.NewGroupClient(m.cli.Conn())
	return client.GetGroupJoinRequests(ctx, in, opts...)
}

// 获取用户发出的入群申请
func (m *defaultGroup) GetSentJoinRequests(ctx context.Context, in *GetSentJoinRequestsReq, opts ...grpc.CallOption) (*GetSentJoinRequestsResp, error) {
	client := group.NewGroupClient(m.cli.Conn())
	return client.GetSentJoinRequests(ctx, in, opts...)
}

// 获取所有管理群组的入群申请（通知中心）
func (m *defaultGroup) GetAllManagedGroupJoinRequests(ctx context.Context, in *GetAllManagedGroupJoinRequestsReq, opts ...grpc.CallOption) (*GetAllManagedGroupJoinRequestsResp, error) {
	client := group.NewGroupClient(m.cli.Conn())
	return client.GetAllManagedGroupJoinRequests(ctx, in, opts...)
}
