// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: group.proto

package server

import (
	"context"

	"SkyeIM/app/group/rpc/group"
	"SkyeIM/app/group/rpc/internal/logic"
	"SkyeIM/app/group/rpc/internal/svc"
)

type GroupServer struct {
	svcCtx *svc.ServiceContext
	group.UnimplementedGroupServer
}

func NewGroupServer(svcCtx *svc.ServiceContext) *GroupServer {
	return &GroupServer{
		svcCtx: svcCtx,
	}
}

// 创建群组
func (s *GroupServer) CreateGroup(ctx context.Context, in *group.CreateGroupReq) (*group.CreateGroupResp, error) {
	l := logic.NewCreateGroupLogic(ctx, s.svcCtx)
	return l.CreateGroup(in)
}

// 获取群组信息
func (s *GroupServer) GetGroupInfo(ctx context.Context, in *group.GetGroupInfoReq) (*group.GetGroupInfoResp, error) {
	l := logic.NewGetGroupInfoLogic(ctx, s.svcCtx)
	return l.GetGroupInfo(in)
}

// 更新群组信息
func (s *GroupServer) UpdateGroup(ctx context.Context, in *group.UpdateGroupReq) (*group.UpdateGroupResp, error) {
	l := logic.NewUpdateGroupLogic(ctx, s.svcCtx)
	return l.UpdateGroup(in)
}

// 解散群组
func (s *GroupServer) DismissGroup(ctx context.Context, in *group.DismissGroupReq) (*group.DismissGroupResp, error) {
	l := logic.NewDismissGroupLogic(ctx, s.svcCtx)
	return l.DismissGroup(in)
}

// 邀请成员加入群组
func (s *GroupServer) InviteMembers(ctx context.Context, in *group.InviteMembersReq) (*group.InviteMembersResp, error) {
	l := logic.NewInviteMembersLogic(ctx, s.svcCtx)
	return l.InviteMembers(in)
}

// 踢出成员
func (s *GroupServer) KickMember(ctx context.Context, in *group.KickMemberReq) (*group.KickMemberResp, error) {
	l := logic.NewKickMemberLogic(ctx, s.svcCtx)
	return l.KickMember(in)
}

// 退出群组
func (s *GroupServer) QuitGroup(ctx context.Context, in *group.QuitGroupReq) (*group.QuitGroupResp, error) {
	l := logic.NewQuitGroupLogic(ctx, s.svcCtx)
	return l.QuitGroup(in)
}

// 获取群成员列表
func (s *GroupServer) GetMemberList(ctx context.Context, in *group.GetMemberListReq) (*group.GetMemberListResp, error) {
	l := logic.NewGetMemberListLogic(ctx, s.svcCtx)
	return l.GetMemberList(in)
}

// 获取用户的群组列表
func (s *GroupServer) GetUserGroupList(ctx context.Context, in *group.GetUserGroupListReq) (*group.GetUserGroupListResp, error) {
	l := logic.NewGetUserGroupListLogic(ctx, s.svcCtx)
	return l.GetUserGroupList(in)
}

// 设置成员权限
func (s *GroupServer) SetMemberRole(ctx context.Context, in *group.SetMemberRoleReq) (*group.SetMemberRoleResp, error) {
	l := logic.NewSetMemberRoleLogic(ctx, s.svcCtx)
	return l.SetMemberRole(in)
}

// 设置成员禁言
func (s *GroupServer) SetMemberMute(ctx context.Context, in *group.SetMemberMuteReq) (*group.SetMemberMuteResp, error) {
	l := logic.NewSetMemberMuteLogic(ctx, s.svcCtx)
	return l.SetMemberMute(in)
}

// 检查用户是否在群组中
func (s *GroupServer) CheckMembership(ctx context.Context, in *group.CheckMembershipReq) (*group.CheckMembershipResp, error) {
	l := logic.NewCheckMembershipLogic(ctx, s.svcCtx)
	return l.CheckMembership(in)
}

// 更新群组已读进度
func (s *GroupServer) UpdateGroupReadSeq(ctx context.Context, in *group.UpdateGroupReadSeqReq) (*group.UpdateGroupReadSeqResp, error) {
	l := logic.NewUpdateGroupReadSeqLogic(ctx, s.svcCtx)
	return l.UpdateGroupReadSeq(in)
}

// 获取用户加入的群组列表（包含成员信息如ReadSeq）
func (s *GroupServer) GetJoinedGroups(ctx context.Context, in *group.GetJoinedGroupsReq) (*group.GetJoinedGroupsResp, error) {
	l := logic.NewGetJoinedGroupsLogic(ctx, s.svcCtx)
	return l.GetJoinedGroups(in)
}

// 模糊搜索群组
func (s *GroupServer) SearchGroup(ctx context.Context, in *group.SearchGroupReq) (*group.SearchGroupResp, error) {
	l := logic.NewSearchGroupLogic(ctx, s.svcCtx)
	return l.SearchGroup(in)
}

// ==================== 群聊邀请相关 ====================
func (s *GroupServer) SendGroupInvitation(ctx context.Context, in *group.SendGroupInvitationReq) (*group.SendGroupInvitationResp, error) {
	l := logic.NewSendGroupInvitationLogic(ctx, s.svcCtx)
	return l.SendGroupInvitation(in)
}

// 处理群聊邀请（同意/拒绝）
func (s *GroupServer) HandleGroupInvitation(ctx context.Context, in *group.HandleGroupInvitationReq) (*group.HandleGroupInvitationResp, error) {
	l := logic.NewHandleGroupInvitationLogic(ctx, s.svcCtx)
	return l.HandleGroupInvitation(in)
}

// 获取收到的群聊邀请列表
func (s *GroupServer) GetReceivedInvitations(ctx context.Context, in *group.GetReceivedInvitationsReq) (*group.GetReceivedInvitationsResp, error) {
	l := logic.NewGetReceivedInvitationsLogic(ctx, s.svcCtx)
	return l.GetReceivedInvitations(in)
}

// 获取发出的群聊邀请列表
func (s *GroupServer) GetSentInvitations(ctx context.Context, in *group.GetSentInvitationsReq) (*group.GetSentInvitationsResp, error) {
	l := logic.NewGetSentInvitationsLogic(ctx, s.svcCtx)
	return l.GetSentInvitations(in)
}

// ==================== 入群申请相关 ====================
func (s *GroupServer) SendJoinRequest(ctx context.Context, in *group.SendJoinRequestReq) (*group.SendJoinRequestResp, error) {
	l := logic.NewSendJoinRequestLogic(ctx, s.svcCtx)
	return l.SendJoinRequest(in)
}

// 处理入群申请（群主/管理员）
func (s *GroupServer) HandleJoinRequest(ctx context.Context, in *group.HandleJoinRequestReq) (*group.HandleJoinRequestResp, error) {
	l := logic.NewHandleJoinRequestLogic(ctx, s.svcCtx)
	return l.HandleJoinRequest(in)
}

// 获取群的入群申请列表（群主/管理员查看）
func (s *GroupServer) GetGroupJoinRequests(ctx context.Context, in *group.GetGroupJoinRequestsReq) (*group.GetGroupJoinRequestsResp, error) {
	l := logic.NewGetGroupJoinRequestsLogic(ctx, s.svcCtx)
	return l.GetGroupJoinRequests(in)
}

// 获取用户发出的入群申请
func (s *GroupServer) GetSentJoinRequests(ctx context.Context, in *group.GetSentJoinRequestsReq) (*group.GetSentJoinRequestsResp, error) {
	l := logic.NewGetSentJoinRequestsLogic(ctx, s.svcCtx)
	return l.GetSentJoinRequests(in)
}

// 获取所有管理群组的入群申请（通知中心）
func (s *GroupServer) GetAllManagedGroupJoinRequests(ctx context.Context, in *group.GetAllManagedGroupJoinRequestsReq) (*group.GetAllManagedGroupJoinRequestsResp, error) {
	l := logic.NewGetAllManagedGroupJoinRequestsLogic(ctx, s.svcCtx)
	return l.GetAllManagedGroupJoinRequests(in)
}
