// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: user.proto

package userclient

import (
	"context"

	"SkyeIM/app/user/rpc/user"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	BatchGetUsersRequest   = user.BatchGetUsersRequest
	BatchGetUsersResponse  = user.BatchGetUsersResponse
	CheckUserExistRequest  = user.CheckUserExistRequest
	CheckUserExistResponse = user.CheckUserExistResponse
	GetUserRequest         = user.GetUserRequest
	GetUserResponse        = user.GetUserResponse
	SearchUserRequest      = user.SearchUserRequest
	SearchUserResponse     = user.SearchUserResponse
	UpdateUserRequest      = user.UpdateUserRequest
	UpdateUserResponse     = user.UpdateUserResponse
	UserInfo               = user.UserInfo

	User interface {
		// 获取单个用户信息
		GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*GetUserResponse, error)
		// 批量获取用户信息（消息列表、群成员列表等场景）
		BatchGetUsers(ctx context.Context, in *BatchGetUsersRequest, opts ...grpc.CallOption) (*BatchGetUsersResponse, error)
		// 搜索用户（用于添加好友）
		SearchUser(ctx context.Context, in *SearchUserRequest, opts ...grpc.CallOption) (*SearchUserResponse, error)
		// 更新用户信息
		UpdateUser(ctx context.Context, in *UpdateUserRequest, opts ...grpc.CallOption) (*UpdateUserResponse, error)
		// 检查用户是否存在
		CheckUserExist(ctx context.Context, in *CheckUserExistRequest, opts ...grpc.CallOption) (*CheckUserExistResponse, error)
	}

	defaultUser struct {
		cli zrpc.Client
	}
)

func NewUser(cli zrpc.Client) User {
	return &defaultUser{
		cli: cli,
	}
}

// 获取单个用户信息
func (m *defaultUser) GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*GetUserResponse, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.GetUser(ctx, in, opts...)
}

// 批量获取用户信息（消息列表、群成员列表等场景）
func (m *defaultUser) BatchGetUsers(ctx context.Context, in *BatchGetUsersRequest, opts ...grpc.CallOption) (*BatchGetUsersResponse, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.BatchGetUsers(ctx, in, opts...)
}

// 搜索用户（用于添加好友）
func (m *defaultUser) SearchUser(ctx context.Context, in *SearchUserRequest, opts ...grpc.CallOption) (*SearchUserResponse, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.SearchUser(ctx, in, opts...)
}

// 更新用户信息
func (m *defaultUser) UpdateUser(ctx context.Context, in *UpdateUserRequest, opts ...grpc.CallOption) (*UpdateUserResponse, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.UpdateUser(ctx, in, opts...)
}

// 检查用户是否存在
func (m *defaultUser) CheckUserExist(ctx context.Context, in *CheckUserExistRequest, opts ...grpc.CallOption) (*CheckUserExistResponse, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.CheckUserExist(ctx, in, opts...)
}
