// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: user.proto

package server

import (
	"context"

	"SkyeIM/app/user/rpc/internal/logic"
	"SkyeIM/app/user/rpc/internal/svc"
	"SkyeIM/app/user/rpc/user"
)

type UserServer struct {
	svcCtx *svc.ServiceContext
	user.UnimplementedUserServer
}

func NewUserServer(svcCtx *svc.ServiceContext) *UserServer {
	return &UserServer{
		svcCtx: svcCtx,
	}
}

// 获取单个用户信息
func (s *UserServer) GetUser(ctx context.Context, in *user.GetUserRequest) (*user.GetUserResponse, error) {
	l := logic.NewGetUserLogic(ctx, s.svcCtx)
	return l.GetUser(in)
}

// 批量获取用户信息（消息列表、群成员列表等场景）
func (s *UserServer) BatchGetUsers(ctx context.Context, in *user.BatchGetUsersRequest) (*user.BatchGetUsersResponse, error) {
	l := logic.NewBatchGetUsersLogic(ctx, s.svcCtx)
	return l.BatchGetUsers(in)
}

// 搜索用户（用于添加好友）
func (s *UserServer) SearchUser(ctx context.Context, in *user.SearchUserRequest) (*user.SearchUserResponse, error) {
	l := logic.NewSearchUserLogic(ctx, s.svcCtx)
	return l.SearchUser(in)
}

// 更新用户信息
func (s *UserServer) UpdateUser(ctx context.Context, in *user.UpdateUserRequest) (*user.UpdateUserResponse, error) {
	l := logic.NewUpdateUserLogic(ctx, s.svcCtx)
	return l.UpdateUser(in)
}

// 检查用户是否存在
func (s *UserServer) CheckUserExist(ctx context.Context, in *user.CheckUserExistRequest) (*user.CheckUserExistResponse, error) {
	l := logic.NewCheckUserExistLogic(ctx, s.svcCtx)
	return l.CheckUserExist(in)
}
