// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type UploadAvatarResp struct {
	Url       string `json:"url"`       // 头像URL
	Thumbnail string `json:"thumbnail"` // 缩略图URL
}

type UploadFileResp struct {
	Url      string `json:"url"`      // 文件URL
	Filename string `json:"filename"` // 文件名
	Size     int64  `json:"size"`     // 文件大小（字节）
	MimeType string `json:"mimeType"` // MIME类型
}

type UploadImageResp struct {
	Url       string `json:"url"`       // 图片URL
	Thumbnail string `json:"thumbnail"` // 缩略图URL（可选）
	Width     int32  `json:"width"`     // 图片宽度
	Height    int32  `json:"height"`    // 图片高度
	Size      int64  `json:"size"`      // 文件大小（字节）
}
