// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.20.3
// source: message.proto

package message

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// MessageClient is the client API for Message service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MessageClient interface {
	// 发送私聊消息（存储到数据库）
	SendMessage(ctx context.Context, in *SendMessageReq, opts ...grpc.CallOption) (*SendMessageResp, error)
	// 发送群聊消息
	SendGroupMessage(ctx context.Context, in *SendGroupMessageReq, opts ...grpc.CallOption) (*SendGroupMessageResp, error)
	// 获取私聊历史消息列表（分页）
	GetMessageList(ctx context.Context, in *GetMessageListReq, opts ...grpc.CallOption) (*GetMessageListResp, error)
	// 获取群聊历史消息列表（分页）
	GetGroupMessageList(ctx context.Context, in *GetGroupMessageListReq, opts ...grpc.CallOption) (*GetGroupMessageListResp, error)
	// 标记私聊消息为已读
	MarkAsRead(ctx context.Context, in *MarkAsReadReq, opts ...grpc.CallOption) (*MarkAsReadResp, error)
	// 获取私聊未读消息数量
	GetUnreadCount(ctx context.Context, in *GetUnreadCountReq, opts ...grpc.CallOption) (*GetUnreadCountResp, error)
	// 获取私聊未读消息列表
	GetUnreadMessages(ctx context.Context, in *GetUnreadMessagesReq, opts ...grpc.CallOption) (*GetUnreadMessagesResp, error)
	// 获取大于指定Seq的群聊消息 (用于消息同步)
	GetGroupMessagesBySeq(ctx context.Context, in *GetGroupMessagesBySeqReq, opts ...grpc.CallOption) (*GetGroupMessagesBySeqResp, error)
	// 模糊搜索消息内容
	SearchMessage(ctx context.Context, in *SearchMessageReq, opts ...grpc.CallOption) (*SearchMessageResp, error)
	// 获取@我的消息列表
	GetAtMeMessages(ctx context.Context, in *GetAtMeMessagesReq, opts ...grpc.CallOption) (*GetAtMeMessagesResp, error)
}

type messageClient struct {
	cc grpc.ClientConnInterface
}

func NewMessageClient(cc grpc.ClientConnInterface) MessageClient {
	return &messageClient{cc}
}

func (c *messageClient) SendMessage(ctx context.Context, in *SendMessageReq, opts ...grpc.CallOption) (*SendMessageResp, error) {
	out := new(SendMessageResp)
	err := c.cc.Invoke(ctx, "/message.Message/SendMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageClient) SendGroupMessage(ctx context.Context, in *SendGroupMessageReq, opts ...grpc.CallOption) (*SendGroupMessageResp, error) {
	out := new(SendGroupMessageResp)
	err := c.cc.Invoke(ctx, "/message.Message/SendGroupMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageClient) GetMessageList(ctx context.Context, in *GetMessageListReq, opts ...grpc.CallOption) (*GetMessageListResp, error) {
	out := new(GetMessageListResp)
	err := c.cc.Invoke(ctx, "/message.Message/GetMessageList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageClient) GetGroupMessageList(ctx context.Context, in *GetGroupMessageListReq, opts ...grpc.CallOption) (*GetGroupMessageListResp, error) {
	out := new(GetGroupMessageListResp)
	err := c.cc.Invoke(ctx, "/message.Message/GetGroupMessageList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageClient) MarkAsRead(ctx context.Context, in *MarkAsReadReq, opts ...grpc.CallOption) (*MarkAsReadResp, error) {
	out := new(MarkAsReadResp)
	err := c.cc.Invoke(ctx, "/message.Message/MarkAsRead", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageClient) GetUnreadCount(ctx context.Context, in *GetUnreadCountReq, opts ...grpc.CallOption) (*GetUnreadCountResp, error) {
	out := new(GetUnreadCountResp)
	err := c.cc.Invoke(ctx, "/message.Message/GetUnreadCount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageClient) GetUnreadMessages(ctx context.Context, in *GetUnreadMessagesReq, opts ...grpc.CallOption) (*GetUnreadMessagesResp, error) {
	out := new(GetUnreadMessagesResp)
	err := c.cc.Invoke(ctx, "/message.Message/GetUnreadMessages", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageClient) GetGroupMessagesBySeq(ctx context.Context, in *GetGroupMessagesBySeqReq, opts ...grpc.CallOption) (*GetGroupMessagesBySeqResp, error) {
	out := new(GetGroupMessagesBySeqResp)
	err := c.cc.Invoke(ctx, "/message.Message/GetGroupMessagesBySeq", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageClient) SearchMessage(ctx context.Context, in *SearchMessageReq, opts ...grpc.CallOption) (*SearchMessageResp, error) {
	out := new(SearchMessageResp)
	err := c.cc.Invoke(ctx, "/message.Message/SearchMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageClient) GetAtMeMessages(ctx context.Context, in *GetAtMeMessagesReq, opts ...grpc.CallOption) (*GetAtMeMessagesResp, error) {
	out := new(GetAtMeMessagesResp)
	err := c.cc.Invoke(ctx, "/message.Message/GetAtMeMessages", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MessageServer is the server API for Message service.
// All implementations must embed UnimplementedMessageServer
// for forward compatibility
type MessageServer interface {
	// 发送私聊消息（存储到数据库）
	SendMessage(context.Context, *SendMessageReq) (*SendMessageResp, error)
	// 发送群聊消息
	SendGroupMessage(context.Context, *SendGroupMessageReq) (*SendGroupMessageResp, error)
	// 获取私聊历史消息列表（分页）
	GetMessageList(context.Context, *GetMessageListReq) (*GetMessageListResp, error)
	// 获取群聊历史消息列表（分页）
	GetGroupMessageList(context.Context, *GetGroupMessageListReq) (*GetGroupMessageListResp, error)
	// 标记私聊消息为已读
	MarkAsRead(context.Context, *MarkAsReadReq) (*MarkAsReadResp, error)
	// 获取私聊未读消息数量
	GetUnreadCount(context.Context, *GetUnreadCountReq) (*GetUnreadCountResp, error)
	// 获取私聊未读消息列表
	GetUnreadMessages(context.Context, *GetUnreadMessagesReq) (*GetUnreadMessagesResp, error)
	// 获取大于指定Seq的群聊消息 (用于消息同步)
	GetGroupMessagesBySeq(context.Context, *GetGroupMessagesBySeqReq) (*GetGroupMessagesBySeqResp, error)
	// 模糊搜索消息内容
	SearchMessage(context.Context, *SearchMessageReq) (*SearchMessageResp, error)
	// 获取@我的消息列表
	GetAtMeMessages(context.Context, *GetAtMeMessagesReq) (*GetAtMeMessagesResp, error)
	mustEmbedUnimplementedMessageServer()
}

// UnimplementedMessageServer must be embedded to have forward compatible implementations.
type UnimplementedMessageServer struct {
}

func (UnimplementedMessageServer) SendMessage(context.Context, *SendMessageReq) (*SendMessageResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendMessage not implemented")
}
func (UnimplementedMessageServer) SendGroupMessage(context.Context, *SendGroupMessageReq) (*SendGroupMessageResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendGroupMessage not implemented")
}
func (UnimplementedMessageServer) GetMessageList(context.Context, *GetMessageListReq) (*GetMessageListResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMessageList not implemented")
}
func (UnimplementedMessageServer) GetGroupMessageList(context.Context, *GetGroupMessageListReq) (*GetGroupMessageListResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGroupMessageList not implemented")
}
func (UnimplementedMessageServer) MarkAsRead(context.Context, *MarkAsReadReq) (*MarkAsReadResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MarkAsRead not implemented")
}
func (UnimplementedMessageServer) GetUnreadCount(context.Context, *GetUnreadCountReq) (*GetUnreadCountResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUnreadCount not implemented")
}
func (UnimplementedMessageServer) GetUnreadMessages(context.Context, *GetUnreadMessagesReq) (*GetUnreadMessagesResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUnreadMessages not implemented")
}
func (UnimplementedMessageServer) GetGroupMessagesBySeq(context.Context, *GetGroupMessagesBySeqReq) (*GetGroupMessagesBySeqResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGroupMessagesBySeq not implemented")
}
func (UnimplementedMessageServer) SearchMessage(context.Context, *SearchMessageReq) (*SearchMessageResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchMessage not implemented")
}
func (UnimplementedMessageServer) GetAtMeMessages(context.Context, *GetAtMeMessagesReq) (*GetAtMeMessagesResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAtMeMessages not implemented")
}
func (UnimplementedMessageServer) mustEmbedUnimplementedMessageServer() {}

// UnsafeMessageServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MessageServer will
// result in compilation errors.
type UnsafeMessageServer interface {
	mustEmbedUnimplementedMessageServer()
}

func RegisterMessageServer(s grpc.ServiceRegistrar, srv MessageServer) {
	s.RegisterService(&Message_ServiceDesc, srv)
}

func _Message_SendMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendMessageReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageServer).SendMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/message.Message/SendMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageServer).SendMessage(ctx, req.(*SendMessageReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Message_SendGroupMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendGroupMessageReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageServer).SendGroupMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/message.Message/SendGroupMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageServer).SendGroupMessage(ctx, req.(*SendGroupMessageReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Message_GetMessageList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMessageListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageServer).GetMessageList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/message.Message/GetMessageList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageServer).GetMessageList(ctx, req.(*GetMessageListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Message_GetGroupMessageList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGroupMessageListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageServer).GetGroupMessageList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/message.Message/GetGroupMessageList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageServer).GetGroupMessageList(ctx, req.(*GetGroupMessageListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Message_MarkAsRead_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MarkAsReadReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageServer).MarkAsRead(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/message.Message/MarkAsRead",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageServer).MarkAsRead(ctx, req.(*MarkAsReadReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Message_GetUnreadCount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUnreadCountReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageServer).GetUnreadCount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/message.Message/GetUnreadCount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageServer).GetUnreadCount(ctx, req.(*GetUnreadCountReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Message_GetUnreadMessages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUnreadMessagesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageServer).GetUnreadMessages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/message.Message/GetUnreadMessages",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageServer).GetUnreadMessages(ctx, req.(*GetUnreadMessagesReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Message_GetGroupMessagesBySeq_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGroupMessagesBySeqReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageServer).GetGroupMessagesBySeq(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/message.Message/GetGroupMessagesBySeq",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageServer).GetGroupMessagesBySeq(ctx, req.(*GetGroupMessagesBySeqReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Message_SearchMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchMessageReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageServer).SearchMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/message.Message/SearchMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageServer).SearchMessage(ctx, req.(*SearchMessageReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Message_GetAtMeMessages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAtMeMessagesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageServer).GetAtMeMessages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/message.Message/GetAtMeMessages",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageServer).GetAtMeMessages(ctx, req.(*GetAtMeMessagesReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Message_ServiceDesc is the grpc.ServiceDesc for Message service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Message_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "message.Message",
	HandlerType: (*MessageServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendMessage",
			Handler:    _Message_SendMessage_Handler,
		},
		{
			MethodName: "SendGroupMessage",
			Handler:    _Message_SendGroupMessage_Handler,
		},
		{
			MethodName: "GetMessageList",
			Handler:    _Message_GetMessageList_Handler,
		},
		{
			MethodName: "GetGroupMessageList",
			Handler:    _Message_GetGroupMessageList_Handler,
		},
		{
			MethodName: "MarkAsRead",
			Handler:    _Message_MarkAsRead_Handler,
		},
		{
			MethodName: "GetUnreadCount",
			Handler:    _Message_GetUnreadCount_Handler,
		},
		{
			MethodName: "GetUnreadMessages",
			Handler:    _Message_GetUnreadMessages_Handler,
		},
		{
			MethodName: "GetGroupMessagesBySeq",
			Handler:    _Message_GetGroupMessagesBySeq_Handler,
		},
		{
			MethodName: "SearchMessage",
			Handler:    _Message_SearchMessage_Handler,
		},
		{
			MethodName: "GetAtMeMessages",
			Handler:    _Message_GetAtMeMessages_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "message.proto",
}
