// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	blacklist "SkyeIM/app/friend/api/internal/handler/blacklist"
	friend "SkyeIM/app/friend/api/internal/handler/friend"
	request "SkyeIM/app/friend/api/internal/handler/request"
	"SkyeIM/app/friend/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// 设置黑名单
				Method:  http.MethodPost,
				Path:    "/blacklist",
				Handler: blacklist.SetBlacklistHandler(serverCtx),
			},
			{
				// 获取黑名单列表
				Method:  http.MethodGet,
				Path:    "/blacklist",
				Handler: blacklist.GetBlacklistHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1/friend"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 删除好友
				Method:  http.MethodDelete,
				Path:    "/:friendId",
				Handler: friend.DeleteFriendHandler(serverCtx),
			},
			{
				// 检查是否为好友
				Method:  http.MethodGet,
				Path:    "/:friendId/check",
				Handler: friend.IsFriendHandler(serverCtx),
			},
			{
				// 更新好友备注
				Method:  http.MethodPut,
				Path:    "/:friendId/remark",
				Handler: friend.UpdateFriendRemarkHandler(serverCtx),
			},
			{
				// 获取好友列表
				Method:  http.MethodGet,
				Path:    "/list",
				Handler: friend.GetFriendListHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1/friend"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 发送好友申请
				Method:  http.MethodPost,
				Path:    "/request",
				Handler: request.AddFriendRequestHandler(serverCtx),
			},
			{
				// 处理好友申请
				Method:  http.MethodPut,
				Path:    "/request/:requestId",
				Handler: request.HandleFriendRequestHandler(serverCtx),
			},
			{
				// 获取收到的好友申请列表
				Method:  http.MethodGet,
				Path:    "/request/received",
				Handler: request.GetFriendRequestListHandler(serverCtx),
			},
			{
				// 获取发出的好友申请列表
				Method:  http.MethodGet,
				Path:    "/request/sent",
				Handler: request.GetSentRequestListHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1/friend"),
	)
}
