// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	public "auth/internal/handler/public"
	user "auth/internal/handler/user"
	"auth/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// 发送邮箱验证码
				Method:  http.MethodPost,
				Path:    "/captcha/send",
				Handler: public.SendCaptchaHandler(serverCtx),
			},
			{
				// 用户登录
				Method:  http.MethodPost,
				Path:    "/login",
				Handler: public.LoginHandler(serverCtx),
			},
			{
				// 忘记密码
				Method:  http.MethodPost,
				Path:    "/password/forgot",
				Handler: public.ForgotPasswordHandler(serverCtx),
			},
			{
				// 刷新Token
				Method:  http.MethodPost,
				Path:    "/refresh",
				Handler: public.RefreshTokenHandler(serverCtx),
			},
			{
				// 用户注册
				Method:  http.MethodPost,
				Path:    "/register",
				Handler: public.RegisterHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/auth"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 退出登录
				Method:  http.MethodPost,
				Path:    "/logout",
				Handler: user.LogoutHandler(serverCtx),
			},
			{
				// 修改密码
				Method:  http.MethodPost,
				Path:    "/password/change",
				Handler: user.ChangePasswordHandler(serverCtx),
			},
			{
				// 获取用户信息
				Method:  http.MethodGet,
				Path:    "/userinfo",
				Handler: user.GetUserInfoHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1/auth"),
	)
}
