// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	upload "SkyeIM/app/upload/api/internal/handler/upload"
	"SkyeIM/app/upload/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// 上传头像（用户/群组）
				Method:  http.MethodPost,
				Path:    "/avatar",
				Handler: upload.UploadAvatarHandler(serverCtx),
			},
			{
				// 上传文件（文档/视频等）
				Method:  http.MethodPost,
				Path:    "/file",
				Handler: upload.UploadFileHandler(serverCtx),
			},
			{
				// 上传图片（聊天/朋友圈）
				Method:  http.MethodPost,
				Path:    "/image",
				Handler: upload.UploadImageHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1/upload"),
		rest.WithMaxBytes(10485760),
	)
}
