// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type ConversationInfo struct {
	PeerId      int64       `json:"peerId"`      // 对方用户ID
	LastMessage MessageInfo `json:"lastMessage"` // 最后一条消息
	UnreadCount int64       `json:"unreadCount"` // 未读消息数
}

type Empty struct {
}

type GetConversationsResp struct {
	List []ConversationInfo `json:"list"`
}

type GetMessageHistoryReq struct {
	PeerId    int64 `form:"peerId"`             // 对方用户ID
	LastMsgId int64 `form:"lastMsgId,optional"` // 最后一条消息ID（用于分页）
	Limit     int32 `form:"limit,default=20"`   // 获取条数
}

type GetMessageHistoryResp struct {
	List    []MessageInfo `json:"list"`
	HasMore bool          `json:"hasMore"`
}

type GetUnreadCountReq struct {
	PeerId int64 `form:"peerId,optional"` // 对方用户ID，为空则获取所有未读
}

type GetUnreadCountResp struct {
	Count int64 `json:"count"`
}

type MarkAsReadReq struct {
	PeerId int64    `json:"peerId"`          // 对方用户ID
	MsgIds []string `json:"msgIds,optional"` // 消息ID列表，为空则标记所有
}

type MarkAsReadResp struct {
	Count int64 `json:"count"` // 标记的消息数量
}

type MessageInfo struct {
	Id          int64  `json:"id"`
	MsgId       string `json:"msgId"`
	FromUserId  int64  `json:"fromUserId"`
	ToUserId    int64  `json:"toUserId"`
	Content     string `json:"content"`
	ContentType int32  `json:"contentType"` // 1-文字 2-图片 3-文件 4-语音
	Status      int32  `json:"status"`      // 0-未读 1-已读 2-撤回
	CreatedAt   int64  `json:"createdAt"`
}
