// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type ChangePasswordRequest struct {
	OldPassword string `json:"oldPassword" validate:"required"`
	NewPassword string `json:"newPassword" validate:"required,min=6,max=32"`
}

type ChangePasswordResponse struct {
	Message string `json:"message"`
}

type Empty struct {
}

type LoginRequest struct {
	Username string `json:"username" validate:"required"`
	Password string `json:"password" validate:"required"`
}

type RefreshTokenRequest struct {
	RefreshToken string `json:"refreshToken" validate:"required"`
}

type RegisterRequest struct {
	Username string `json:"username" validate:"required,min=3,max=32"`
	Password string `json:"password" validate:"required,min=6,max=32"`
	Email    string `json:"email" validate:"required,email"`
	Captcha  string `json:"captcha" validate:"required,len=6"`
	Phone    string `json:"phone,optional"`
	Nickname string `json:"nickname,optional"`
}

type ForgotPasswordRequest struct {
	Email       string `json:"email" validate:"required,email"`
	Captcha     string `json:"captcha" validate:"required,len=6"`
	NewPassword string `json:"newPassword" validate:"required,min=6,max=32"`
}

type ForgotPasswordResponse struct {
	Message string `json:"message"`
}

type SendCaptchaRequest struct {
	Email string `json:"email" validate:"required,email"`
	Type  string `json:"type" validate:"required,oneof=register reset"` // register=注册, reset=重置密码
}

type SendCaptchaResponse struct {
	Message string `json:"message"`
}

type TokenResponse struct {
	AccessToken  string `json:"accessToken"`
	RefreshToken string `json:"refreshToken"`
	ExpiresIn    int64  `json:"expiresIn"`
}

type UserInfoResponse struct {
	Id       int64  `json:"id"`
	Username string `json:"username"`
	Phone    string `json:"phone"`
	Email    string `json:"email"`
	Nickname string `json:"nickname"`
	Avatar   string `json:"avatar"`
	Status   int64  `json:"status"`
}
