// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type CreateGroupReq struct {
	Name        string  `json:"name"`
	Avatar      string  `json:"avatar,optional"`
	Description string  `json:"description,optional"`
	MaxMembers  int32   `json:"maxMembers,optional"`
	MemberIds   []int64 `json:"memberIds,optional"`
}

type CreateGroupResp struct {
	GroupId string `json:"groupId"`
}

type DismissGroupReq struct {
	GroupId string `json:"groupId"`
}

type GetGroupInfoReq struct {
	GroupId string `path:"groupId"`
}

type GetGroupListReq struct {
	Page     int32 `form:"page,default=1"`
	PageSize int32 `form:"pageSize,default=20"`
}

type GetGroupListResp struct {
	List  []GroupInfo `json:"list"`
	Total int64       `json:"total"`
}

type GetInvitationsReq struct {
	Page     int32 `form:"page,default=1"`
	PageSize int32 `form:"pageSize,default=20"`
}

type GetInvitationsResp struct {
	List  []GroupInvitationInfo `json:"list"`
	Total int64                 `json:"total"`
}

type GetJoinRequestsReq struct {
	Page     int32  `form:"page,default=1"`
	PageSize int32  `form:"pageSize,default=20"`
	GroupId  string `form:"groupId,optional"` // 管理员查询时需要
}

type GetJoinRequestsResp struct {
	List  []JoinRequestInfo `json:"list"`
	Total int64             `json:"total"`
}

type GetMemberListReq struct {
	GroupId  string `form:"groupId"`
	Page     int32  `form:"page,default=1"`
	PageSize int32  `form:"pageSize,default=20"`
}

type GetMemberListResp struct {
	List  []MemberInfo `json:"list"`
	Total int64        `json:"total"`
}

type GroupInfo struct {
	GroupId     string `json:"groupId"`
	Name        string `json:"name"`
	Avatar      string `json:"avatar"`
	OwnerId     int64  `json:"ownerId"`
	Description string `json:"description"`
	MemberCount int32  `json:"memberCount"`
	MaxMembers  int32  `json:"maxMembers"`
	Status      int32  `json:"status"`
	CreatedAt   int64  `json:"createdAt"`
	UpdatedAt   int64  `json:"updatedAt"`
}

type GroupInvitationInfo struct {
	Id          int64  `json:"id"`
	GroupId     string `json:"groupId"`
	GroupName   string `json:"groupName"`
	InviterId   int64  `json:"inviterId"`
	InviterName string `json:"inviterName"`
	InviteeId   int64  `json:"inviteeId"`
	InviteeName string `json:"inviteeName"`
	Message     string `json:"message"`
	Status      int64  `json:"status"`
	CreatedAt   int64  `json:"createdAt"`
}

type HandleGroupInvitationReq struct {
	InvitationId int64 `json:"invitationId"`
	Action       int64 `json:"action"`
}

type HandleJoinRequestReq struct {
	RequestId int64 `json:"requestId"`
	Action    int64 `json:"action"` // 1-同意 2-拒绝
}

type InviteMembersReq struct {
	GroupId   string  `json:"groupId"`
	MemberIds []int64 `json:"memberIds"`
}

type InviteMembersResp struct {
	SuccessCount int32   `json:"successCount"`
	FailedIds    []int64 `json:"failedIds"`
}

type JoinRequestInfo struct {
	Id          int64  `json:"id"`
	GroupId     string `json:"groupId"`
	GroupName   string `json:"groupName"`
	GroupAvatar string `json:"groupAvatar"`
	UserId      int64  `json:"userId"`
	UserName    string `json:"userName"`
	UserAvatar  string `json:"userAvatar"`
	Message     string `json:"message"`
	Status      int64  `json:"status"`
	HandlerId   int64  `json:"handlerId,optional"`
	CreatedAt   int64  `json:"createdAt"`
}

type KickMemberReq struct {
	GroupId  string `json:"groupId"`
	MemberId int64  `json:"memberId"`
}

type MemberInfo struct {
	UserId   int64  `json:"userId"`
	Nickname string `json:"nickname"`
	Avatar   string `json:"avatar"`
	Role     int32  `json:"role"`
	Mute     int32  `json:"mute"`
	JoinTime int64  `json:"joinTime"`
	JoinedAt string `json:"joinedAt"`
	ReadSeq  uint64 `json:"readSeq"`
}

type QuitGroupReq struct {
	GroupId string `json:"groupId"`
}

type Response struct {
	Code    int32       `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type SearchGroupPreciseReq struct {
	GroupId string `form:"groupId"`
}

type SearchGroupReq struct {
	Keyword string `form:"keyword"`
}

type SearchGroupResp struct {
	List  []GroupInfo `json:"list"`
	Total int64       `json:"total"`
}

type SendGroupInvitationReq struct {
	GroupId   string `json:"groupId"`
	InviteeId int64  `json:"inviteeId"`
	Message   string `json:"message,optional"`
}

type SendGroupInvitationResp struct {
	InvitationId int64 `json:"invitationId"`
}

type SendJoinRequestReq struct {
	GroupId string `json:"groupId"`
	Message string `json:"message,optional"`
}

type SendJoinRequestResp struct {
	RequestId int64 `json:"requestId"`
}

type SetMemberMuteReq struct {
	GroupId  string `json:"groupId"`
	MemberId int64  `json:"memberId"`
	Mute     int32  `json:"mute"`
}

type SetMemberRoleReq struct {
	GroupId  string `json:"groupId"`
	MemberId int64  `json:"memberId"`
	Role     int32  `json:"role"`
}

type UpdateGroupReadSeqReq struct {
	GroupId string `json:"groupId"`
	ReadSeq uint64 `json:"readSeq"`
}

type UpdateGroupReq struct {
	GroupId     string `json:"groupId"`
	Name        string `json:"name,optional"`
	Avatar      string `json:"avatar,optional"`
	Description string `json:"description,optional"`
	MaxMembers  int32  `json:"maxMembers,optional"`
}
