// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type Empty struct {
}

type GetUserRequest struct {
	Id int64 `path:"id"`
}

type GlobalSearchRequest struct {
	Keyword string `form:"keyword"`
}

type GlobalSearchResponse struct {
	Users  []UserInfo  `json:"users"`
	Groups []GroupInfo `json:"groups"` // 需同步导入 Group 类型，或者在这里定义一个简版
}

type GroupInfo struct {
	GroupId     string `json:"groupId"`
	Name        string `json:"name"`
	Avatar      string `json:"avatar"`
	Description string `json:"description"`
}

type ProfileResponse struct {
	User UserInfo `json:"user"`
}

type SearchUserRequest struct {
	Keyword string `form:"keyword" validate:"required"`
}

type SearchUserResponse struct {
	Users []UserInfo `json:"users"`
	Total int64      `json:"total"`
}

type UpdateAvatarRequest struct {
	Avatar string `json:"avatar" validate:"required"`
}

type UpdateProfileRequest struct {
	Nickname  string `json:"nickname,optional"`
	Avatar    string `json:"avatar,optional"`
	Signature string `json:"signature,optional"`
	Gender    int64  `json:"gender,optional"`
	Region    string `json:"region,optional"`
	Phone     string `json:"phone,optional"`
}

type UserInfo struct {
	Id        int64  `json:"id"`
	Username  string `json:"username"`
	Nickname  string `json:"nickname"`
	Avatar    string `json:"avatar"`
	Signature string `json:"signature"`
	Gender    int64  `json:"gender"`
	Region    string `json:"region"`
	Phone     string `json:"phone"`
	Email     string `json:"email"`
	Status    int64  `json:"status"`
	CreatedAt int64  `json:"createdAt"`
}
