// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type Empty struct {
}

type GetUserRequest struct {
	Id int64 `path:"id"`
}

type ProfileResponse struct {
	User UserInfo `json:"user"`
}

type SearchUserRequest struct {
	Keyword string `form:"keyword" validate:"required"`
}

type SearchUserResponse struct {
	Users []UserInfo `json:"users"`
	Total int64      `json:"total"`
}

type UpdateAvatarRequest struct {
	Avatar string `json:"avatar" validate:"required"`
}

type UpdateProfileRequest struct {
	Nickname string `json:"nickname,optional"`
	Avatar   string `json:"avatar,optional"`
	Phone    string `json:"phone,optional"`
}

type UserInfo struct {
	Id        int64  `json:"id"`
	Username  string `json:"username"`
	Nickname  string `json:"nickname"`
	Avatar    string `json:"avatar"`
	Phone     string `json:"phone"`
	Email     string `json:"email"`
	Status    int64  `json:"status"`
	CreatedAt int64  `json:"createdAt"`
}
